In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [23]:
fbref_url = "https://fbref.com{}"
premier_league = fbref_url.format("/en/comps/9/Premier-League-Stats")
data = requests.get(premier_league)

In [7]:
pd.read_csv('NEO4J Setup/all_players.csv')

,Unnamed: 0,position,footed,height,weight,dob,birth_place,national_team,club,wages,contract_expiry,img
0,Luca Williams Barnett,FW,NaN,NaN,NaN,01/10/2008,"England, England, United Kingdom",Englandeng,Tottenham Hotspur,NaN,NaN,NaN
1,Wesley Okoduwa,FW,NaN,NaN,NaN,12/05/2008,"England, United Kingdom",NaN,Wolverhampton Wanderers,NaN,NaN,NaN
2,Malachi Hardy,DF,NaN,NaN,NaN,10/03/2008,"England, England, United Kingdom",Englandeng,Tottenham Hotspur,NaN,NaN,NaN
3,Godwill Kukonki,DF,NaN,NaN,NaN,06/02/2008,"England, England, United Kingdom",NaN,Manchester United,NaN,NaN,NaN
4,Mikey Moore,FW,Right,NaN,NaN,11/08/2007,"England, United Kingdom",Englandeng,Tottenham Hotspur,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
595,James Milner,DF-MF (CM-FB-WM),Right,176cm,69kg,04/01/1986,"Leeds, England, United Kingdom",Englandeng,Brighton & Hove Albion,"￡ 60,000 Weekly",Jun-25,https://fbref.com/req/202302030/images/headsho...
596,Scott Carson,GK,Right,192cm,86kg,03/09/1985,"Whitehaven, England, United Kingdom",Englandeng,Manchester City,"￡ 30,000 Weekly",Jun-25,https://fbref.com/req/202302030/images/headsho...
597,Ashley Young,"DF-FW-MF (FB-WM, left)",Right,175cm,63kg,09/07/1985,"Stevenage, England, United Kingdom",Englandeng,Everton,"￡ 40,000 Weekly",Jun-25,https://fbref.com/req/202302030/images/headsho...
598,Łukasz Fabiański,GK,Right,190cm,83kg,18/04/1985,"Kostrzyn nad Odrą, Poland",Polandpl,West Ham United,"￡ 65,000 Weekly",Jun-25,https://fbref.com/req/202302030/images/headsho...
599,Joe O'Brien-Whitmarsh,FW,NaN,NaN,NaN,NaN,NaN,NaN,Southampton,NaN,NaN,NaN

## Retrieving Individual Player Data

In [43]:
all_players_dict

{'Wes Morgan': {'position': 'DF (CB, right)',
  'footed': 'Right',
  'height': '188cm',
  'weight': '93kg',
  'national_team': 'JamaicajmOther',
  'img': 'https://fbref.com/req/202302030/images/headshots/80c31c97_2022.jpg'},
 'Kasper Schmeichel': {'position': 'GK',
  'footed': 'Right',
  'height': '189cm',
  'weight': '83kg',
  'dob': '1986-11-05',
  'birth_place': 'Copenhagen, Denmark',
  'national_team': 'Denmarkdk',
  'club': 'Celtic',
  'wages': '€ 76,154 Weekly',
  'contract_expiry': 'June 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/53af52f3_2022.jpg'},
 'Jamie Vardy': {'position': 'FW',
  'footed': 'Right',
  'height': '178cm',
  'weight': '76kg',
  'dob': '1987-01-11',
  'birth_place': 'Sheffield, England, United Kingdom',
  'national_team': 'Englandeng',
  'club': 'Leicester City',
  'wages': '￡ 140,000 Weekly',
  'contract_expiry': 'June 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/45963054_2022.jpg'},
 'Riyad Mahrez': {'position': 'FW-MF (AM-WM, right)',
  'footed': 'Left',
  'height': '178cm',
  'weight': '59kg',
  'dob': '1991-02-21',
  'birth_place': 'Sarcelles, France',
  'national_team': 'AlgeriadzOther',
  'club': 'Al-Ahli',
  'wages': '￡ 160,000 Weekly',
  'contract_expiry': 'June 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/892d5bb1_2022.jpg'},
 'Robert Huth': {'position': 'DF (CB)',
  'footed': 'Right',
  'height': '191cm',
  'weight': '87kg',
  'national_team': 'Germanyde',
  'img': 'https://fbref.com/req/202302030/images/headshots/0bd1ea64_2022.jpg'},
 'Danny Drinkwater': {'position': 'MF (CM-DM)',
  'footed': 'Right',
  'height': '178cm',
  'weight': '69kg',
  'national_team': 'Englandeng',
  'img': 'https://fbref.com/req/202302030/images/headshots/2649ff32_2022.jpg'},
 'Marc Albrighton': {'position': 'DF-FW-MF (AM-WM)',
  'footed': 'Right',
  'height': '175cm',
  'weight': '67kg',
  'national_team': 'Englandeng',
  'img': 'https://fbref.com/req/202302030/images/headshots/b827d5b3_2022.jpg'},
 "N'Golo Kanté": {'position': 'MF (CM-DM-WM)',
  'footed': 'Right',
  'height': '169cm',
  'weight': '68kg',
  'dob': '1991-03-29',
  'birth_place': 'Paris, France',
  'national_team': 'Francefr',
  'club': 'Al Ittihad Jeddah',
  'img': 'https://fbref.com/req/202302030/images/headshots/b9fbae28_2022.jpg'},
 'Christian Fuchs': {'position': 'DF-MF (FB, left)',
  'footed': 'Left',
  'height': '186cm',
  'weight': '79kg',
  'national_team': 'Austriaat',
  'img': 'https://fbref.com/req/202302030/images/headshots/a67a09fb_2022.jpg'},
 'Danny Simpson': {'position': 'DF (FB, right)',
  'footed': 'Right',
  'height': '178cm',
  'weight': '72kg',
  'img': 'https://fbref.com/req/202302030/images/headshots/3201b03d_2022.jpg'},
 'Shinji Okazaki': {'position': 'FW-MF',
  'footed': 'Right',
  'height': '174cm',
  'weight': '76kg',
  'national_team': 'Japanjp',
  'img': 'https://fbref.com/req/202302030/images/headshots/68796d61_2022.jpg'},
 'Jeffrey Schlupp': {'position': 'DF-FW-MF (FB-WM, left)',
  'footed': 'Left',
  'height': '178cm',
  'weight': '72kg',
  'dob': '1992-12-23',
  'birth_place': 'Hamburg, Germany',
  'national_team': 'GhanaghOther',
  'club': 'Crystal Palace',
  'wages': '￡ 60,000 Weekly',
  'contract_expiry': 'June 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/3312f911_2022.jpg'},
 'Andy King': {'position': 'MF (CM)',
  'footed': 'Right',
  'height': '183cm',
  'weight': '73kg',
  'national_team': 'WaleswlsOther',
  'img': 'https://fbref.com/req/202302030/images/headshots/d790907f_2022.jpg'},
 'Leonardo Ulloa': {'position': 'FW',
  'footed': 'Right',
  'height': '190cm',
  'weight': '79kg',
  'img': 'https://fbref.com/req/202302030/images/headshots/eed56f6c_2022.jpg'},
 'Ritchie De Laet': {'position': 'DF (FB)',
  'footed': 'Right',
  'height': '186cm',
  'weight': '79kg',
  'national_team': 'Belgiumbe',
  'img': 'https://fbref.com/req/202302030/images/headshots/dc234f98_2022.jpg'},
 'Marcin Wasilewski': {'position': 'DF (CB-FB)',
  'footed': 'Right',
  'height': '186cm',
  'weight': '87kg',
  'national_team': 'Polandpl',
  'img': 'https://fbref.com/req/202302030/images/headshots/24249219_2022.jpg'},
 'Gökhan Inler': {'position': 'MF (CM-DM)',
  'footed': 'Both',
  'height': '183cm',
  'weight': '79kg',
  'national_team': 'Switzerlandch',
  'img': 'https://fbref.com/req/202302030/images/headshots/3200c583_2022.jpg'},
 'Demarai Gray': {'position': 'FW-MF (AM-WM)',
  'footed': 'Right',
  'height': '178cm',
  'weight': '66kg',
  'dob': '1996-06-28',
  'birth_place': 'Birmingham, England, United Kingdom',
  'national_team': 'JamaicajmOther',
  'club': 'Al-Ettifaq',
  'img': 'https://fbref.com/req/202302030/images/headshots/4468ec10_2022.jpg'},
 'Daniel Amartey': {'position': 'DF-MF (CB, right)',
  'footed': 'Right',
  'height': '182cm',
  'weight': '76kg',
  'dob': '1994-12-21',
  'birth_place': 'Accra, Ghana',
  'national_team': 'Ghanagh',
  'club': 'Beşiktaş',
  'img': 'https://fbref.com/req/202302030/images/headshots/1a4ef233_2022.jpg'},
 'Nathan Dyer': {'position': 'FW-MF (WM, right)',
  'footed': 'Right',
  'height': '165cm',
  'weight': '57kg',
  'img': 'https://fbref.com/req/202302030/images/headshots/6dfd5af0_2022.jpg'},
 'Yohan Benalouane': {'position': 'DF (CB-FB)',
  'footed': 'Left',
  'height': '187cm',
  'weight': '84kg',
  'national_team': 'TunisiatnOther',
  'img': 'https://fbref.com/req/202302030/images/headshots/8309b068_2022.jpg'},
 'Andrej Kramarić': {'position': 'FW-MF (AM-CM)',
  'footed': 'Right',
  'height': '180cm',
  'weight': '74kg',
  'dob': '1991-06-19',
  'birth_place': 'Zagreb, Croatia',
  'national_team': 'Croatiahr',
  'club': 'Hoffenheim',
  'wages': '€ 76,923 Weekly',
  'contract_expiry': 'June 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/603cb947_2022.jpg'},
 'Joe Dodoo': {'position': 'FW-MF',
  'footed': 'Right',
  'height': '183cm',
  'weight': '79kg',
  'national_team': 'Englandeng',
  'img': 'https://fbref.com/req/202302030/images/headshots/beed85c7_2022.jpg'},
 'Ben Chilwell': {'position': 'DF-MF (FB, left)',
  'footed': 'Left',
  'height': '178cm',
  'weight': '71kg',
  'dob': '1996-12-21',
  'birth_place': 'Milton Keynes, England, United Kingdom',
  'national_team': 'Englandeng',
  'club': 'Chelsea',
  'wages': '￡ 200,000 Weekly',
  'contract_expiry': 'June 2027',
  'img': 'https://fbref.com/req/202302030/images/headshots/d2424d1b_2022.jpg'},
 'Dean Hammond': {'position': 'MF',
  'footed': 'Right',
  'height': '183cm',
  'weight': '73kg',
  'img': 'https://fbref.com/req/202302030/images/headshots/577c12e5_2022.jpg'},
 'Jonny Maddison': {'position': 'GK',
  'footed': 'Right',
  'height': '187cm',
  'weight': '76kg',
  'img': 'https://fbref.com/req/202302030/images/headshots/d9be4784_2022.jpg'},
 'Mark Schwarzer': {'position': 'GK',
  'footed': 'Right',
  'height': '194cm',
  'weight': '84kg',
  'national_team': 'Australiaau',
  'img': 'https://fbref.com/req/202302030/images/headshots/da409c6f_2022.jpg'},
 'Nacho Monreal': {'position': 'DF (FB, left)',
  'footed': 'Left',
  'height': '178cm',
  'weight': '72kg',
  'national_team': 'Spaines',
  'img': 'https://fbref.com/req/202302030/images/headshots/d4cb83cc_2022.jpg'},
 'Héctor Bellerín': {'position': 'DF-MF (FB, right)',
  'footed': 'Right',
  'height': '177cm',
  'weight': '73kg',
  'dob': '1995-03-19',
  'birth_place': 'Barcelona, Spain',
  'national_team': 'Spaines',
  'club': 'Real Betis',
  'wages': '€ 60,000 Weekly',
  'contract_expiry': 'June 2028',
  'img': 'https://fbref.com/req/202302030/images/headshots/f874dd44_2022.jpg'},
 'Mesut Özil': {'position': 'MF (AM-WM)',
  'footed': 'Left',
  'height': '183cm',
  'weight': '74kg',
  'national_team': 'Germanyde',
  'img': 'https://fbref.com/req/202302030/images/headshots/16380240_2022.jpg'},
 'Petr Čech': {'position': 'GK',
  'footed': 'Left',
  'height': '196cm',
  'weight': '89kg',
  'national_team': 'Czech Republiccz',
  'img': 'https://fbref.com/req/202302030/images/headshots/71672fa0_2022.jpg'},
 'Laurent Koscielny': {'position': 'DF (CB)',
  'footed': 'Right',
  'height': '186cm',
  'weight': '74kg',
  'national_team': 'Francefr',
  'img': 'https://fbref.com/req/202302030/images/headshots/f5efb153_2022.jpg'},
 'Aaron Ramsey': {'position': 'MF (AM-CM-DM)',
  'footed': 'Right',
  'height': '182cm',
  'weight': '72kg',
  'dob': '1990-12-26',
  'birth_place': 'Caerphilly, Wales, United Kingdom',
  'national_team': 'Waleswls',
  'club': 'Cardiff City',
  'img': 'https://fbref.com/req/202302030/images/headshots/ef619b0b_2022.jpg'},
 'Alexis Sánchez': {'position': 'FW-MF (AM-WM)',
  'footed': 'Right',
  'height': '168cm',
  'weight': '62kg',
  'dob': '1988-12-19',
  'birth_place': 'Tocopilla, Chile',
  'national_team': 'Chilecl',
  'club': 'Udinese',
  'wages': '€ 53,462 Weekly',
  'contract_expiry': 'June 2026',
  'img': 'https://fbref.com/req/202302030/images/headshots/2c0f8e9e_2022.jpg'},
 'Olivier Giroud': {'position': 'FW',
  'footed': 'Left',
  'height': '192cm',
  'weight': '87kg',
  'dob': '1986-09-30',
  'birth_place': 'Chambéry, France',
  'national_team': 'Francefr',
  'club': 'Los Angeles FC',
  'wages': '$2,800,000 Annual',
  'contract_expiry': 'December 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/16ceb862_2022.jpg'},
 'Per Mertesacker': {'position': 'DF (CB)',
  'footed': 'Right',
  'height': '198cm',
  'weight': '89kg',
  'national_team': 'Germanyde',
  'img': 'https://fbref.com/req/202302030/images/headshots/5be28712_2022.jpg'},
 'Francis Coquelin': {'position': 'DF-MF (CM-DM-FB)',
  'footed': 'Right',
  'height': '178cm',
  'weight': '73kg',
  'national_team': 'Francefr',
  'img': 'https://fbref.com/req/202302030/images/headshots/a6951bf8_2022.jpg'},
 'Gabriel Paulista': {'position': 'DF (CB)',
  'footed': 'Right',
  'height': '187cm',
  'weight': '86kg',
  'dob': '1990-11-26',
  'birth_place': 'Fortaleza, Brazil',
  'club': 'Beşiktaş',
  'img': 'https://fbref.com/req/202302030/images/headshots/b7ca5c51_2022.jpg'},
 'Theo Walcott': {'position': 'FW-MF (AM-WM, right)',
  'footed': 'Right',
  'height': '176cm',
  'weight': '69kg',
  'national_team': 'Englandeng',
  'img': 'https://fbref.com/req/202302030/images/headshots/1ecb65be_2022.jpg'},
 'Santi Cazorla': {'position': 'MF (AM-WM)',
  'footed': 'Right',
  'height': '165cm',
  'weight': '66kg',
  'dob': '1984-12-13',
  'birth_place': 'Lugo de Llanera, Spain',
  'national_team': 'Spaines',
  'club': 'Oviedo',
  'img': 'https://fbref.com/req/202302030/images/headshots/e2e9c250_2022.jpg'},
 'Mathieu Flamini': {'position': 'MF (DM)',
  'footed': 'Both',
  'height': '178cm',
  'weight': '67kg',
  'national_team': 'Francefr',
  'img': 'https://fbref.com/req/202302030/images/headshots/148d4105_2022.jpg'},
 'Joel Campbell': {'position': 'FW-MF (AM)',
  'footed': 'Left',
  'height': '178cm',
  'weight': '69kg',
  'dob': '1992-06-26',
  'birth_place': 'San José, Costa Rica',
  'national_team': 'Costa Ricacr',
  'club': 'Atlético Goianiense',
  'img': 'https://fbref.com/req/202302030/images/headshots/895ff3ca_2022.jpg'},
 'Alex Oxlade-Chamberlain': {'position': 'FW-MF (CM-WM)',
  'footed': 'Right',
  'height': '180cm',
  'weight': '74kg',
  'dob': '1993-08-15',
  'birth_place': 'Portsmouth, England, United Kingdom',
  'national_team': 'Englandeng',
  'club': 'Beşiktaş',
  'img': 'https://fbref.com/req/202302030/images/headshots/38c7feef_2022.jpg'},
 'Mohamed Elneny': {'position': 'MF (CM-DM)',
  'footed': 'Right',
  'height': '180cm',
  'weight': '77kg',
  'dob': '1992-07-11',
  'birth_place': 'Al Maḩallah al Kubrá, Egypt',
  'national_team': 'Egypteg',
  'club': 'Al Jazira',
  'img': 'https://fbref.com/req/202302030/images/headshots/47a34c4f_2022.jpg'},
 'Alex Iwobi': {'position': 'FW-MF (AM-CM-WM)',
  'footed': 'Right',
  'height': '180cm',
  'weight': '74kg',
  'dob': '1996-05-03',
  'birth_place': 'Lagos, Nigeria',
  'national_team': 'NigeriangOther',
  'club': 'Fulham',
  'wages': '￡ 80,000 Weekly',
  'contract_expiry': 'June 2028',
  'img': 'https://fbref.com/req/202302030/images/headshots/6ca5ec4b_2022.jpg'},
 'Danny Welbeck': {'position': 'FW-MF (WM)',
  'footed': 'Right',
  'height': '185cm',
  'weight': '72kg',
  'dob': '1990-11-26',
  'birth_place': 'Manchester, England, United Kingdom',
  'national_team': 'Englandeng',
  'club': 'Brighton & Hove Albion',
  'wages': '￡ 60,000 Weekly',
  'contract_expiry': 'June 2026',
  'img': 'https://fbref.com/req/202302030/images/headshots/ce5143da_2022.jpg'},
 'David Ospina': {'position': 'GK',
  'footed': 'Right',
  'height': '183cm',
  'weight': '76kg',
  'dob': '1988-08-31',
  'birth_place': 'Medellín, Colombia',
  'national_team': 'Colombiaco',
  'club': 'Atlético Nacional',
  'img': 'https://fbref.com/req/202302030/images/headshots/82b1198a_2022.jpg'},
 'Kieran Gibbs': {'position': 'DF-MF (FB, left)',
  'footed': 'Left',
  'height': '178cm',
  'weight': '63kg',
  'national_team': 'Englandeng',
  'img': 'https://fbref.com/req/202302030/images/headshots/46ee5234_2022.jpg'},
 'Calum Chambers': {'position': 'DF-MF (CB-FB)',
  'footed': 'Right',
  'height': '183cm',
  'weight': '77kg',
  'dob': '1995-01-20',
  'birth_place': 'Petersfield, England, United Kingdom',
  'national_team': 'Englandeng',
  'club': 'Cardiff City',
  'wages': '￡ 50,000 Weekly',
  'contract_expiry': 'June 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/dc6f5bdd_2022.jpg'},
 'Mathieu Debuchy': {'position': 'DF (FB, right)',
  'footed': 'Right',
  'height': '177cm',
  'weight': '73kg',
  'national_team': 'Francefr',
  'img': 'https://fbref.com/req/202302030/images/headshots/92232aad_2022.jpg'},
 'Jack Wilshere': {'position': 'MF',
  'footed': 'Left',
  'height': '172cm',
  'weight': '66kg',
  'national_team': 'Englandeng',
  'img': 'https://fbref.com/req/202302030/images/headshots/9c318325_2022.jpg'},
 'Mikel Arteta': {'position': 'MF',
  'footed': 'Right',
  'height': '177cm',
  'weight': '64kg',
  'national_team': 'Spaines',
  'img': 'https://fbref.com/req/202302030/images/headshots/d934d1e6_2022.jpg'},
 'Matt Macey': {'position': 'GK',
  'footed': 'Right',
  'height': '198cm',
  'weight': '81kg',
  'dob': '1994-09-09',
  'birth_place': 'Bath, England, United Kingdom',
  'club': 'Colchester United',
  'img': 'https://fbref.com/req/202302030/images/headshots/136e7649_2022.jpg'},
 'Jeff Reine-Adélaïde': {'position': 'FW-MF',
  'footed': 'Right',
  'height': '183cm',
  'weight': '76kg',
  'dob': '1998-01-17',
  'birth_place': 'Champigny-sur-Marne, France',
  'national_team': 'Francefr',
  'club': 'Salernitana',
  'img': 'https://fbref.com/req/202302030/images/headshots/d504b3e1_2022.jpg'},
 'Toby Alderweireld': {'position': 'DF (CB-FB)',
  'footed': 'Right',
  'height': '187cm',
  'weight': '79kg',
  'dob': '1989-03-02',
  'birth_place': 'Wilrijk, Belgium',
  'national_team': 'Belgiumbe',
  'club': 'Antwerp',
  'img': 'https://fbref.com/req/202302030/images/headshots/f7d50789_2022.jpg'},
 'Harry Kane': {'position': 'FW',
  'footed': 'Right',
  'height': '188cm',
  'weight': '73kg',
  'dob': '1993-07-28',
  'birth_place': 'Walthamstow, England, United Kingdom',
  'national_team': 'Englandeng',
  'club': 'Bayern Munich',
  'wages': '€ 480,769 Weekly',
  'contract_expiry': 'June 2027',
  'img': 'https://fbref.com/req/202302030/images/headshots/21a66f6a_2022.jpg'},
 'Hugo Lloris': {'position': 'GK',
  'footed': 'Left',
  'height': '188cm',
  'weight': '78kg',
  'dob': '1986-12-26',
  'birth_place': 'Nice, France',
  'national_team': 'Francefr',
  'club': 'Los Angeles FC',
  'wages': '$350,000 Annual',
  'contract_expiry': 'December 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/8f62b6ee_2022.jpg'},
 'Eric Dier': {'position': 'DF-MF (CB-DM)',
  'footed': 'Right',
  'height': '188cm',
  'weight': '87kg',
  'dob': '1994-01-15',
  'birth_place': 'Cheltenham, England, United Kingdom',
  'national_team': 'Englandeng',
  'club': 'Bayern Munich',
  'wages': '€ 96,154 Weekly',
  'contract_expiry': 'June 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/ac861941_2022.jpg'},
 'Kyle Walker': {'position': 'DF-MF (FB, right)',
  'footed': 'Right',
  'height': '178cm',
  'weight': '73kg',
  'dob': '1990-05-28',
  'birth_place': 'Sheffield, England, United Kingdom',
  'national_team': 'Englandeng',
  'club': 'Manchester City',
  'wages': '￡ 175,000 Weekly',
  'contract_expiry': 'June 2026',
  'img': 'https://fbref.com/req/202302030/images/headshots/86dd77d1_2022.jpg'},
 'Christian Eriksen': {'position': 'FW-MF (AM-CM-DM)',
  'footed': 'Right',
  'height': '177cm',
  'weight': '67kg',
  'dob': '1992-02-14',
  'birth_place': 'Middelfart, Denmark',
  'national_team': 'Denmarkdk',
  'club': 'Manchester United',
  'wages': '￡ 150,000 Weekly',
  'contract_expiry': 'June 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/980522ec_2022.jpg'},
 'Jan Vertonghen': {'position': 'DF (CB-FB, left)',
  'footed': 'Left',
  'height': '189cm',
  'weight': '86kg',
  'dob': '1987-04-24',
  'birth_place': 'Sint-Niklaas, Belgium',
  'national_team': 'Belgiumbe',
  'club': 'Anderlecht',
  'img': 'https://fbref.com/req/202302030/images/headshots/ba23a904_2022.jpg'},
 'Dele Alli': {'position': 'FW-MF (AM)',
  'footed': 'Right',
  'height': '188cm',
  'weight': '76kg',
  'national_team': 'Englandeng',
  'wages': '€  Weekly',
  'contract_expiry': 'June 2026',
  'img': 'https://fbref.com/req/202302030/images/headshots/cea4ee8f_2022.jpg'},
 'Érik Lamela': {'position': 'FW-MF (AM-WM, right)',
  'footed': 'Left',
  'height': '184cm',
  'weight': '72kg',
  'dob': '1992-03-04',
  'birth_place': 'Buenos Aires, Argentina',
  'national_team': 'Argentinaar',
  'club': 'AEK Athens',
  'img': 'https://fbref.com/req/202302030/images/headshots/abe66106_2022.jpg'},
 'Mousa Dembélé': {'position': 'MF (DM)',
  'footed': 'Left',
  'height': '185cm',
  'weight': '83kg',
  'national_team': 'Belgiumbe',
  'img': 'https://fbref.com/req/202302030/images/headshots/f7ee69fb_2022.jpg'},
 'Danny Rose': {'position': 'DF-MF (FB, left)',
  'footed': 'Left',
  'height': '173cm',
  'weight': '68kg',
  'national_team': 'Englandeng',
  'img': 'https://fbref.com/req/202302030/images/headshots/89d10e53_2022.jpg'},
 'Ben Davies': {'position': 'DF-MF (CB-FB, left)',
  'footed': 'Left',
  'height': '181cm',
  'weight': '76kg',
  'dob': '1993-04-24',
  'birth_place': 'Neath, Wales, United Kingdom',
  'national_team': 'Waleswls',
  'club': 'Tottenham Hotspur',
  'wages': '￡ 80,000 Weekly',
  'contract_expiry': 'June 2025',
  'img': 'https://fbref.com/req/202302030/images/headshots/44781702_2022.jpg'},
 'Son Heung-min': {'position': 'FW-MF (AM-WM)',
  'footed': 'Right',
  'height': '183cm',
  'weight': '76kg',
  'dob': '1992-07-08',
  'birth_place': 'Chuncheon, Korea Republic',
  'national_team': 'Korea Republickr',
  'club': 'Tottenham Hotspur',
  'wages': '￡ 190,000 Weekly',
  'contract_expiry': 'June 2026',
  'img': 'https://fbref.com/req/202302030/images/headshots/92e7e919_2022.jpg'},
 'Nacer Chadli': {'position': 'FW-MF (AM-WM)',
  'footed': 'Right',
  'height': '187cm',
  'weight': '78kg',
  'dob': '1989-08-02',
  'birth_place': 'Liège, Belgium',
  'national_team': 'Belgiumbe',
  'club': 'Royal Standard de Liège U23',
  'img': 'https://fbref.com/req/202302030/images/headshots/5b54bf3b_2022.jpg'},
 'Kevin Wimmer': {'position': 'DF (CB, left)',
  'footed': 'Left',
  'height': '187cm',
  'weight': '84kg',
  'dob': '1992-11-15',
  'birth_place': 'Wels Stadt, Austria',
  'national_team': 'Austriaat',
  'club': 'ŠK Slovan Bratislava',
  'img': 'https://fbref.com/req/202302030/images/headshots/faf55ce4_2022.jpg'},
 'Ryan Mason': {'position': 'MF',
  'footed': 'Right',
  'height': '175cm',
  'weight': '68kg',
  'national_team': 'Englandeng',
  'img': 'https://fbref.com/req/202302030/images/headshots/c8fac933_2022.jpg'},
 'Kieran Trippier': {'position': 'DF-MF (FB, right)',
  'footed': 'Right',
  'height': '178cm',
  'weight': '66kg',
  'dob': '1990-09-19',

In [41]:
with open('players2024-2025.pkl',"rb") as f:
    p24 = pickle.load(f)

In [45]:
p24.update(all_players_dict)

In [47]:
len(p24)

1503

In [49]:
len(all_players_dict)

1861

In [48]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
import pickle
from IPython.display import clear_output


def make_request(endpoint: str) -> str:
    while True:
        response = requests.get(endpoint)
        if response.status_code == 429:  # Rate limited
            print("Rate limited. Pausing for 5 minutes...")
            print(endpoint)
            print(response.text)
            time.sleep(300)  # Wait for 5 minutes
        else:
            return response.text

def get_page_soup(url:str) -> BeautifulSoup:
    return BeautifulSoup(make_request(url), 'html.parser')

def extract_team_links(url:str) -> dict:
    league_teams_soup = get_page_soup(url)
    league_table = league_teams_soup.select('table.stats_table')[0]
    teams_dict = {team_link.get_text():fbref_url.format(team_link.get("href")) for team_link in league_table.find_all('a') if "squads" in team_link.get("href")}
    return teams_dict

def extract_player_links(url:str) -> dict:
    team_soup = get_page_soup(url)
    team_players_table = team_soup.select('table.stats_table')[0]
    players_links_dict = {
            l.get_text():fbref_url.format(l.get("href")) for l in team_players_table.find_all('a') 
            if (link := l.get("href")) and "players" in link and "matchlogs" not in link
        }
    return players_links_dict

def extract_player_details(url:str) -> dict:
    player_soup = get_page_soup(url)
    media_item_div = player_soup.select_one('div.media-item')
    image_src = media_item_div.find('img')['src'] if media_item_div else None
    player_data = dict()
    # Extracting data dynamically
    for p in player_soup.find_all('p'):
        text = p.get_text(strip=True)
        # Extract position and footed
        if "Position:" in text:
            position_part = text.split("▪")[0].strip()
            footed_part = text.split("▪")[1].strip() if "▪" in text else None
            player_data['position'] = position_part.split(":")[1].strip()
            if footed_part:
                player_data['footed'] = footed_part.split(":")[1].strip()
        # Extract height and weight
        if "cm" in text and "kg" in text:
            height, weight = map(str.strip, text.split(',')[:2])
            player_data['height'] = height
            player_data['weight'] = weight.split('(')[0]
        # Extract date of birth and place of birth
        if "Born:" in text:
            birth_data = p.find("span", {"data-birth": True})
            if birth_data:
                player_data['dob'] = birth_data["data-birth"]
                birth_place = birth_data.find_next_sibling("span")
                if birth_place:
                    player_data['birth_place'] = birth_place.get_text(strip=True)[3:]  # Clean prefix if necessary
        # Extract national team
        if "National Team:" in text:
            player_data['national_team'] = text.split(":")[1].strip()
        # Extract club
        if "Club:" in text:
            player_data['club'] = text.split(":")[1].strip()
        # Extract wages and contract expiry
        if "Wages" in text:
            wages = p.select_one('.important').get_text(strip=True) if p.select_one('.important') else None
            player_data['wages'] = wages
            if "Expires" in text:
                contract_expires = text.split("Expires")[1].split(".")[0].strip()
                player_data['contract_expiry'] = contract_expires
    if image_src:
        player_data['img'] = image_src
    return player_data

# URLs
# premier_league_links = ['https://fbref.com/en/comps/9/2015-2016/2015-2016-Premier-League-Stats',
#                         'https://fbref.com/en/comps/9/2023-2024/2023-2024-Premier-League-Stats',
#                         'https://fbref.com/en/comps/9/2022-2023/2022-2023-Premier-League-Stats',
#                        'https://fbref.com/en/comps/9/2021-2022/2021-2022-Premier-League-Stats',
#                        'https://fbref.com/en/comps/9/Premier-League-Stats'
#                        ]
premier_league_links = [
                        'https://fbref.com/en/comps/9/2022-2023/2022-2023-Premier-League-Stats',
                       'https://fbref.com/en/comps/9/2021-2022/2021-2022-Premier-League-Stats'
                       ]

fbref_url = 'https://fbref.com{}'
# Load existing player list from CSV
# all_players_dict = dict()
# with open('players2015-2016.pkl',"rb") as f:
#     all_players_dict = pickle.load(f)
all_players_dict = p24


for premier_league_link in premier_league_links:
    # Fetch Premier League standings
    season_all_players = dict()
    premier_league_season = premier_league_link.split('/')[-2]
    premier_league_season = premier_league_season if premier_league_season != "9" else "2024-2025"
    team_links = extract_team_links(premier_league_link)
    teams_dict = {}
    for team_count, team_data in enumerate(team_links.items()):
        print(f'Team Progress: {(team_count / len(team_links.items())) * 100:.2f}%')
        team_name, team_link = team_data
        player_links = extract_player_links(team_link)

        team_players_list = list()
        for player_count, player_data in enumerate(player_links.items()):
            player_name, player_link = player_data
            print(f'Player Progress: {(player_count / len(player_links.items())) * 100:.2f}%')
            team_players_list.append(player_name)
            if player_name in all_players_dict:
                print(f"{player_name} already in list. Skipping...")
                season_all_players[player_name] = all_players_dict[player_name]
            else:
                player_data = extract_player_details(player_link)
                print(f"Retrieved player data from fbref {player_name}: {player_data}")
                all_players_dict[player_name] = player_data
                season_all_players[player_name] = player_data
                time.sleep(4) 
            # if player_name in all_players_dict:
            #     print(f"{player_name} already in list. Skipping...")
            #     team_players_dict[player_name] = all_players_dict[player_name]
            #     season_all_players[player_name] = all_players_dict[player_name]
            # else:
            #     player_data = extract_player_details(player_link)    
            #     team_players_dict[player_name] = player_data
            #     season_all_players[player_name] = player_data
            #     print(f"Retrieved player data from fbref {player_name}: {player_data}")
            #     time.sleep(4)  
            
        clear_output(wait=True)
        teams_dict[team_name] = team_players_list
        time.sleep(5)
        clear_output(wait=True)
    with open(f'players{premier_league_season}.pkl','wb') as f:
        pickle.dump(season_all_players, f)
    with open(f'teams{premier_league_season}.pkl','wb') as f:
        pickle.dump(teams_dict, f)
    # pd.DataFrame.from_dict(season_all_players).to_csv(f'players{premier_league_year }.csv', index=False)    
    # with open(f'team_dict_{premier_league_year}.pkl', 'wb') as f:
    #     pickle.dump(team_dict, f)
    print(f"Finished processing season: {premier_league_link.split('/')[-2]}")
    time.sleep(60)

Finished processing season: 2021-2022

## Get All Matches

In [885]:
import io

def get_fixtures(url:str) -> BeautifulSoup:
    fixtures_soup = get_page_soup(url)
    fixtures_table = fixtures_soup.find(id='all_sched')
    return fixtures_table

def get_match_data(url:str) -> list:
    game_soup = get_page_soup(url)
    team_stats = list()
    team_game_stats = game_soup.find_all(id=re.compile("all_player_stats"))
    goaly_game_stats = game_soup.find_all(id=re.compile("keeper_stats"), class_ = "table_wrapper")
    for team_stat in team_game_stats:
        team_stats.append(pd.read_html(str(team_stat))[0])
    for count, goaly_stat in enumerate(goaly_game_stats):
        goaly_df = pd.read_html(str(goaly_stat))[0]
        team_stats[count] = [team_stats[count], goaly_df]
    return team_stats


matches_dict = dict()

# quick ovveride:
premier_league_links = ['https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures']
for premiere_league_link in premier_league_links:
    premier_league_year = premier_league_link.split('/')[-2]
    fixtures = get_fixtures(premiere_league_link)
    match_report_links = [fbref_url.format(l.get('href')) for l in fixtures_table.find_all('a') if "Match Report" in l]
    print('LENGTH OF MATCH REPORT LINKS IS: '+str(len(match_report_links)))
    match_reports = list()
    
    for count, match_link  in enumerate(match_report_links):
        print(f"getting match data for match: {link}. Progress: {((count+1)/len(match_report_links))*100}%")
        match_data = get_match_data(match_link)
        match_reports.append(match_data)
        time.sleep(4)
        clear_output()
    matches_dict[premier_league_year] = match_reports

In [865]:
game_stats = matches_dict['9']
with open('game_stats.pkl', "wb") as f:
    pkl.dump(game_stats,f)

In [871]:
game_stats[189][0][0]

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
               Player                  #             Nation
0     Dominic Solanke               19.0            eng ENG
1         Timo Werner               16.0             de GER
2       Son Heung-min                7.0             kr KOR
3     Brennan Johnson               22.0            wls WAL
4    Dejan Kulusevski               21.0             se SWE
5     Pape Matar Sarr               29.0             sn SEN
6       Yves Bissouma                8.0             ml MLI
7      Lucas Bergvall               15.0             se SWE
8      James Maddison               10.0            eng ENG
9         Djed Spence               24.0            eng ENG
10        Archie Gray               14.0            eng ENG
11      Radu Drăgușin                6.0             ro ROU
12    Sergio Reguilón                3.0             es ESP
13        Pedro Porro               23.0             es ESP
14     Brandon Austin               40.0            eng ENG
15         15 Players                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Performance      \
                  Pos                Age                Min         Gls Ast
0                  FW             27-112                 90           1   0
1                  LW             28-304                 61           0   0
2                  LW             32-180                 29           0   0
3                  RW             23-226                 90           0   0
4               AM,RM             24-254                 90           0   0
5                  DM             22-112                 61           0   0
6                  CM             28-127                 29           0   0
7                  DM             18-337                 61           0   0
8                  LM             28-042                 29           0   0
9               CB,LB             24-148                 90           0   0
10                 CB             18-298                 90           0   0
11                 CB             22-336                 45           0   0
12                 LB             28-019                 45           0   0
13                 RB             25-113                 90           0   1
14                 GK             25-362                 90           0   0
15                NaN                NaN                990           1   1

             ... SCA     Passes                 Carries      Take-Ons
   PK PKatt  ... SCA GCA    Cmp  Att  Cmp% PrgP Carries PrgC      Att Succ
0   0     0  ...   2   0      9   17  52.9    1      15    1        2    0
1   0     0  ...   0   0     11   16  68.8    3      11    3        1    0
2   0     0  ...   2   0     24   27  88.9    2      24    2        4    1
3   0     0  ...   5   1     17   22  77.3    3      19    3        2    1
4   0     0  ...   5   0     28   38  73.7    7      38    5        1    1
5   0     0  ...   2   0     27   33  81.8    4      23    0        1    0
6   0     0  ...   0   0     29   30  96.7    4      22    2        0    0
7   0     0  ...   0   0     29   36  80.6    3      27    3        3    1
8   0     0  ...   1   0     31   35  88.6    7      30    2        0    0
9   0     0  ...   0   0     46   61  75.4    4      40    0        2    0
10  0     0  ...   0   0     46   53  86.8    2      36    0        0    0
11  0     0  ...   0   0      9   16  56.3    0      13    0        0    0
12  0     0  ...   0   0     30   41  73.2    4      28    0        2    1
13  0     0  ...   5   1     39   55  70.9    2      33    2        0    0
14  0     0  ...   0   0     22   32  68.8    0      22    0        0    0
15  0     0  ...  22   2    397  512  77.5   46     381   23       18    5

[16 rows x 31 columns]

In [875]:
x = get_fixtures('https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures')

In [877]:
pd.read_html(str(x))[0]

/var/folders/78/b2j3spl172n6y7p_sw2jggr40000gn/T/ipykernel_54417/126797153.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(str(x))[0]

,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes
0,1.0,Fri,2024-08-16,20:00,Manchester Utd,2.4,1–0,0.4,Fulham,73297.0,Old Trafford,Robert Jones,Match Report,NaN
1,1.0,Sat,2024-08-17,12:30,Ipswich Town,0.5,0–2,2.6,Liverpool,30014.0,Portman Road Stadium,Tim Robinson,Match Report,NaN
2,1.0,Sat,2024-08-17,15:00,Newcastle Utd,0.3,1–0,1.8,Southampton,52196.0,St James' Park,Craig Pawson,Match Report,NaN
3,1.0,Sat,2024-08-17,15:00,Nott'ham Forest,1.3,1–1,1.2,Bournemouth,29763.0,The City Ground,Michael Oliver,Match Report,NaN
4,1.0,Sat,2024-08-17,15:00,Everton,0.5,0–3,1.4,Brighton,39217.0,Goodison Park,Simon Hooper,Match Report,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,38.0,Sun,2025-05-25,16:00,Fulham,NaN,NaN,NaN,Manchester City,NaN,Craven Cottage,NaN,Head-to-Head,NaN
414,38.0,Sun,2025-05-25,16:00,Nott'ham Forest,NaN,NaN,NaN,Chelsea,NaN,The City Ground,NaN,Head-to-Head,NaN
415,38.0,Sun,2025-05-25,16:00,Manchester Utd,NaN,NaN,NaN,Aston Villa,NaN,Old Trafford,NaN,Head-to-Head,NaN
416,38.0,Sun,2025-05-25,16:00,Wolves,NaN,NaN,NaN,Brentford,NaN,Molineux Stadium,NaN,Head-to-Head,NaN
417,38.0,Sun,2025-05-25,16:00,Tottenham,NaN,NaN,NaN,Brighton,NaN,Tottenham Hotspur Stadium,NaN,Head-to-Head,NaN

In [804]:
from neo4j import GraphDatabase
from neo4j.exceptions import ServiceUnavailable
import logging
import pandas as pd

NEO4J_URI='neo4j+s://2b521897.databases.neo4j.io'
NEO4J_USERNAME='neo4j'
NEO4J_PASSWORD='nCUihZktDGHjJUpQtKUal0IJhrk0eSuMdSFUm99Th3Q'
AURA_INSTANCEID='2b521897'
AURA_INSTANCENAME='Instance01'

In [803]:
driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD))

In [677]:
# players_df = pd.read_csv('all_players_pd.csv')
print(players_data)

[{'Name': 'Virgil van Dijk', 'position': 'DF (CB, left)', 'footed': 'Right', 'height': '193cm', 'weight': '87kg', 'dob': '1991-07-08', 'birth_place': 'Breda, Netherlands', 'national_team': 'Netherlandsnl', 'club': 'Liverpool', 'wages': '￡ 220,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/e06683ca_2022.jpg'}, {'Name': 'Mohamed Salah', 'position': 'FW-MF (AM-WM, right)', 'footed': 'Left', 'height': '175cm', 'weight': '71kg', 'dob': '1992-06-15', 'birth_place': 'Basyūn, Egypt', 'national_team': 'Egypteg', 'club': 'Liverpool', 'wages': '￡ 350,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/e342ad68_2022.jpg'}, {'Name': 'Ryan Gravenberch', 'position': 'MF (CM-DM-WM)', 'footed': 'Right', 'height': '190cm', 'weight': '78kg', 'dob': '2002-05-16', 'birth_place': 'Amsterdam, Netherlands', 'national_team': 'Netherlandsnl', 'club': 'Liverpool', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/b8e740fb_2022.jpg'}, {'Name': 'Trent Alexander-Arnold', 'position': 'DF (FB, right)', 'footed': 'Right', 'height': '175cm', 'weight': '68kg', 'dob': '1998-10-07', 'birth_place': 'Liverpool, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': '￡ 180,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/cd1acf9d_2022.jpg'}, {'Name': 'Andrew Robertson', 'position': 'DF-MF (FB, left)', 'footed': 'Left', 'height': '178cm', 'weight': '63kg', 'dob': '1994-03-11', 'birth_place': 'Glasgow, Scotland, United Kingdom', 'national_team': 'Scotlandsct', 'club': 'Liverpool', 'wages': '￡ 160,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/2e4f5f03_2022.jpg'}, {'Name': 'Alexis Mac Allister', 'position': 'MF (AM-CM-DM-WM)', 'footed': 'Right', 'height': '174cm', 'weight': '72kg', 'dob': '1998-12-24', 'birth_place': 'Santa Rosa, Argentina', 'national_team': 'Argentinaar', 'club': 'Liverpool', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/83d074ff_2022.jpg'}, {'Name': 'Luis Díaz', 'position': 'FW-MF (AM-WM, left)', 'footed': 'Right', 'height': '180cm', 'weight': '72kg', 'dob': '1997-01-13', 'birth_place': 'Barrancas, Colombia', 'national_team': 'Colombiaco', 'club': 'Liverpool', 'wages': '￡ 55,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/4a1a9578_2022.jpg'}, {'Name': 'Dominik Szoboszlai', 'position': 'FW-MF (AM-CM-WM)', 'footed': 'Right', 'height': '186cm', 'weight': '73kg', 'dob': '2000-10-25', 'birth_place': 'Hungary', 'national_team': 'Hungaryhu', 'club': 'Liverpool', 'wages': '￡ 120,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/934e1968_2022.jpg'}, {'Name': 'Ibrahima Konaté', 'position': 'DF (CB, right)', 'footed': 'Right', 'height': '193cm', 'weight': '83kg', 'dob': '1999-05-25', 'birth_place': 'Paris, France', 'national_team': 'Francefr', 'club': 'Liverpool', 'wages': '￡ 70,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/5ed9b537_2022.jpg'}, {'Name': 'Cody Gakpo', 'position': 'FW-MF (AM)', 'footed': 'Right', 'height': '187cm', 'weight': '78kg', 'dob': '1999-05-07', 'birth_place': 'Gemeente Eindhoven, Netherlands', 'national_team': 'Netherlandsnl', 'club': 'Liverpool', 'wages': '￡ 120,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/1971591f_2022.jpg'}, {'Name': 'Alisson', 'position': 'GK', 'footed': 'Right', 'height': '193cm', 'weight': '91kg', 'dob': '1992-10-02', 'birth_place': 'Novo Hamburgo, Brazil', 'national_team': 'Brazilbr', 'club': 'Liverpool', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/7a2e46a8_2022.jpg'}, {'Name': 'Curtis Jones', 'position': 'FW-MF (CM-WM)', 'footed': 'Right', 'height': '185cm', 'weight': '72kg', 'dob': '2001-01-30', 'birth_place': 'Liverpool, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': '￡ 15,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/4fb9c88f_2022.jpg'}, {'Name': 'Caoimhín Kelleher', 'position': 'GK', 'footed': 'Right', 'height': '188cm', 'weight': '81kg', 'dob': '1998-11-23', 'birth_place': 'Cork, Republic of Ireland', 'national_team': 'Republic of Irelandie', 'club': 'Liverpool', 'wages': '￡ 10,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/62d7ef38_2022.jpg'}, {'Name': 'Darwin Núñez', 'position': 'FW', 'footed': 'Right', 'height': '187cm', 'weight': '79kg', 'dob': '1999-06-24', 'birth_place': 'Artigas, Uruguay', 'national_team': 'Uruguayuy', 'club': 'Liverpool', 'wages': '￡ 140,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/4d77b365_2022.jpg'}, {'Name': 'Diogo Jota', 'position': 'FW-MF', 'footed': 'Right', 'height': '178cm', 'weight': '69kg', 'dob': '1996-12-04', 'birth_place': 'Massarelos, Portugal', 'national_team': 'Portugalpt', 'club': 'Liverpool', 'wages': '￡ 140,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/178ae8f8_2022.jpg'}, {'Name': 'Joe Gomez', 'position': 'DF (CB-FB, right)', 'footed': 'Right', 'height': '188cm', 'weight': '77kg', 'dob': '1997-05-23', 'birth_place': 'Catford, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': '￡ 85,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/7a11550b_2022.jpg'}, {'Name': 'Kostas Tsimikas', 'position': 'DF (FB, left)', 'footed': 'Left', 'height': '177cm', 'weight': '69kg', 'dob': '1996-05-12', 'birth_place': 'Dimos Thessaloniki, Greece', 'national_team': 'Greecegr', 'club': 'Liverpool', 'wages': '￡ 75,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/f315ca93_2022.jpg'}, {'Name': 'Jarell Quansah', 'position': 'DF (CB)', 'footed': nan, 'height': '197cm', 'weight': '79kg', 'dob': '2003-01-29', 'birth_place': 'Warrington, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/4125cb98_2022.jpg'}, {'Name': 'Conor Bradley', 'position': 'DF-MF (FB, right)', 'footed': 'Right', 'height': '181cm', 'weight': '68kg', 'dob': '2003-07-09', 'birth_place': 'Northern Ireland, United Kingdom', 'national_team': 'Northern Irelandnir', 'club': 'Liverpool', 'wages': '￡ 10,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/bbd67769_2022.jpg'}, {'Name': 'Wataru Endo', 'position': 'DF-MF (CM-DM)', 'footed': 'Right', 'height': '178cm', 'weight': '74kg', 'dob': '1993-02-09', 'birth_place': 'Yokohama Shi, Japan', 'national_team': 'Japanjp', 'club': 'Liverpool', 'wages': '￡ 50,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/c149016b_2022.jpg'}, {'Name': 'Harvey Elliott', 'position': 'FW-MF (WM, right)', 'footed': 'Left', 'height': '170cm', 'weight': '67kg', 'dob': '2003-04-04', 'birth_place': 'Chertsey, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': '￡ 40,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/c8387671_2022.jpg'}, {'Name': 'Federico Chiesa', 'position': 'DF-FW-MF (WM)', 'footed': 'Right', 'height': '175cm', 'weight': '69kg', 'dob': '1997-10-25', 'birth_place': 'Genoa, Italy', 'national_team': 'Italyit', 'club': 'Liverpool', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/b0f7e36c_2022.jpg'}, {'Name': 'Vitezslav Jaros', 'position': 'GK', 'footed': 'Right', 'height': '184cm', 'weight': '69kg', 'dob': '2001-07-23', 'birth_place': 'Příbram, Czech Republic', 'national_team': 'Czech Republiccz', 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/12bb4d6a_2022.jpg'}, {'Name': 'Jayden Danns', 'position': 'FW', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-01-16', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': nan}, {'Name': 'Harvey Davies', 'position': 'GK', 'footed': nan, 'height': '186cm', 'weight': '77kg', 'dob': '2003-09-03', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/fd08a24b_2022.jpg'}, {'Name': 'James McConnell', 'position': 'MF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2004-09-13', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': nan}, {'Name': 'Tyler Morton', 'position': 'MF (CM-DM)', 'footed': 'Right', 'height': '178cm', 'weight': '67kg', 'dob': '2002-10-31', 'birth_place': 'England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/2bc28bb9_2022.jpg'}, {'Name': 'Amara Nallo', 'position': 'DF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-11-18', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': nan}, {'Name': 'Trey Nyoni', 'position': 'MF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2007-06-30', 'birth_place': 'England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': nan}, {'Name': 'David Raya', 'position': 'GK', 'footed': 'Right', 'height': '186cm', 'weight': '81kg', 'dob': '1995-09-15', 'birth_place': 'Barcelona, Spain', 'national_team': 'Spaines', 'club': 'Arsenal', 'wages': '￡ 100,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/98ea5115_2022.jpg'}, {'Name': 'William Saliba', 'position': 'DF (CB, right)', 'footed': 'Right', 'height': '193cm', 'weight': '76kg', 'dob': '2001-03-24', 'birth_place': 'Bondy, France', 'national_team': 'Francefr', 'club': 'Arsenal', 'wages': '￡ 190,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/972aeb2a_2022.jpg'}, {'Name': 'Gabriel Magalhães', 'position': 'DF (CB, left)', 'footed': 'Left', 'height': '190cm', 'weight': '78kg', 'dob': '1997-12-19', 'birth_place': 'São Paulo, Brazil', 'national_team': 'Brazilbr', 'club': 'Arsenal', 'wages': '￡ 100,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/67ac5bb8_2022.jpg'}, {'Name': 'Kai Havertz', 'position': 'FW-MF (AM-CM-WM)', 'footed': 'Left', 'height': '186cm', 'weight': '77kg', 'dob': '1999-06-11', 'birth_place': 'Aachen, Germany', 'national_team': 'Germanyde', 'club': 'Arsenal', 'wages': '￡ 280,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/fed7cb61_2022.jpg'}, {'Name': 'Thomas Partey', 'position': 'DF-MF (CM-DM)', 'footed': 'Right', 'height': '185cm', 'weight': '78kg', 'dob': '1993-06-13', 'birth_place': 'Odumase Krobo, Ghana', 'national_team': 'Ghanagh', 'club': 'Arsenal', 'wages': '￡ 200,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/529f49ab_2022.jpg'}, {'Name': 'Jurriën Timber', 'position': 'DF (CB, right)', 'footed': 'Right', 'height': '179cm', 'weight': '78kg', 'dob': '2001-06-17', 'birth_place': 'Utrecht, Netherlands', 'national_team': 'Netherlandsnl', 'club': 'Arsenal', 'wages': '￡ 90,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/41034650_2022.jpg'}, {'Name': 'Declan Rice', 'position': 'DF-MF (CM-DM)', 'footed': 'Right', 'height': '185cm', 'weight': '77kg', 'dob': '1999-01-14', 'birth_place': 'London, England, United Kingdom', 'national_team': 'EnglandengOther', 'club': 'Arsenal', 'wages': '￡ 240,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/1c7012b8_2022.jpg'}, {'Name': 'Bukayo Saka', 'position': 'DF-FW-MF (AM, right)', 'footed': 'Left', 'height': '178cm', 'weight': '64kg', 'dob': '2001-09-05', 'birth_place': 'Ealing, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Arsenal', 'wages': '￡ 195,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/bc7dc64d_2022.jpg'}, {'Name': 'Gabriel Martinelli', 'position': 'FW-MF', 'footed': 'Right', 'height': '180cm', 'weight': '74kg', 'dob': '2001-06-18', 'birth_place': 'Guarulhos, Brazil', 'national_team': 'Brazilbr', 'club': 'Arsenal', 'wages': '￡ 180,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/48a5a5d6_2022.jpg'}, {'Name': 'Leandro Trossard', 'position': 'FW-MF (AM)', 'footed': 'Right', 'height': '172cm', 'weight': '60kg', 'dob': '1994-12-04', 'birth_place': 'Maasmechelen, Belgium', 'national_team': 'Belgiumbe', 'club': 'Arsenal', 'wages': '￡ 90,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/38ceb24a_2022.jpg'}, {'Name': 'Martin Ødegaard', 'position': 'FW-MF (AM-CM-WM)', 'footed': 'Left', 'height': '179cm', 'weight': '68kg', 'dob': '1998-12-17', 'birth_place': 'Drammen, Norway', 'national_team': 'Norwayno', 'club': 'Arsenal', 'wages': '￡ 240,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/79300479_2022.jpg'}, {'Name': 'Riccardo Calafiori', 'position': 'DF', 'footed': 'Left', 'height': '183cm', 'weight': '74kg', 'dob': '2002-05-19', 'birth_place': 'Roma, Italy', 'national_team': 'Italyit', 'club': 'Arsenal', 'wages': '￡ 120,000 Weekly', 'contract_expiry': 'June 2029', 'img': 'https://fbref.com/req/202302030/images/headshots/aded8e6f_2022.jpg'}, {'Name': 'Ben White', 'position': 'DF (CB-FB, right)', 'footed': 'Right', 'height': '182cm', 'weight': '73kg', 'dob': '1997-10-08', 'birth_place': 'Poole, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Arsenal', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/35e413f1_2022.jpg'}, {'Name': 'Mikel Merino', 'position': 'MF (AM-CM-DM-WM)', 'footed': 'Left', 'height': '188cm', 'weight': '78kg', 'dob': '1996-06-22', 'birth_place': 'Pamplona, Spain', 'national_team': 'Spaines', 'club': 'Arsenal', 'wages': '￡ 130,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/d080ed5e_2022.jpg'}, {'Name': 'Gabriel Jesus', 'position': 'FW-MF', 'footed': 'Right', 'height': '177cm', 'weight': '72kg', 'dob': '1997-04-03', 'birth_place': 'São Paulo, Brazil', 'national_team': 'Brazilbr', 'club': 'Arsenal', 'wages': '￡ 265,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/b66315ae_2022.jpg'}, {'Name': 'Jorginho', 'position': 'MF (CM-DM)', 'footed': 'Right', 'height': '180cm', 'weight': '64kg', 'dob': '1991-12-20', 'birth_place': 'Imbituba, Brazil', 'national_team': 'ItalyitOther', 'club': 'Arsenal', 'wages': '￡ 110,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/45db685d_2022.jpg'}, {'Name': 'Myles Lewis-Skelly', 'position': 'MF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-09-26', 'birth_place': 'England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/5dff6c28_2022.jpg'}, {'Name': 'Jakub Kiwior', 'position': 'DF-MF', 'footed': 'Left', 'height': '182cm', 'weight': '78kg', 'dob': '2000-02-15', 'birth_place': 'Tychy, Poland', 'national_team': 'Polandpl', 'club': 'Arsenal', 'wages': '￡ 58,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/dc3e663e_2022.jpg'}, {'Name': 'Ethan Nwaneri', 'position': 'MF', 'footed': nan, 'height': '180cm', 'weight': '82kg', 'dob': '2007-03-21', 'birth_place': 'England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/7f94982c_2022.jpg'}, {'Name': 'Oleksandr Zinchenko', 'position': 'DF-MF (FB, left)', 'footed': 'Left', 'height': '175cm', 'weight': '60kg', 'dob': '1996-12-15', 'birth_place': 'Radomyshl, Ukraine', 'national_team': 'Ukraineua', 'club': 'Arsenal', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/51cf8561_2022.jpg'}, {'Name': 'Raheem Sterling', 'position': 'FW-MF (AM-WM)', 'footed': 'Right', 'height': '170cm', 'weight': '69kg', 'dob': '1994-12-08', 'birth_place': 'Kingston, Jamaica', 'national_team': 'EnglandengOther', 'club': 'Arsenal', 'wages': '￡ 162,500 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/b400bde0_2022.jpg'}, {'Name': 'Takehiro Tomiyasu', 'position': 'DF (CB-FB)', 'footed': 'Right', 'height': '185cm', 'weight': '78kg', 'dob': '1998-11-05', 'birth_place': 'Fukuoka, Japan', 'national_team': 'Japanjp', 'club': 'Arsenal', 'wages': '￡ 100,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/b3af9be1_2022.jpg'}, {'Name': 'Reiss Nelson', 'position': 'FW-MF', 'footed': 'Right', 'height': '175cm', 'weight': '68kg', 'dob': '1999-12-10', 'birth_place': 'Elephant & Castle, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Fulham', 'wages': '￡ 100,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/c5bdb6e3_2022.jpg'}, {'Name': 'Nathan Butler-Oyedeji', 'position': 'FW', 'footed': 'Right', 'height': nan, 'weight': nan, 'dob': '2003-01-04', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/3a686640_2022.jpg'}, {'Name': 'Ayden Heaven', 'position': 'DF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-09-22', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/64e17fab_2022.jpg'}, {'Name': 'Ismeal Kabia', 'position': 'MF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2005-12-10', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/6b15cf32_2022.jpg'}, {'Name': 'Maldini Kacurri', 'position': 'DF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2005-10-04', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/7be4311f_2022.jpg'}, {'Name': 'Neto', 'position': 'GK', 'footed': 'Right', 'height': '193cm', 'weight': '83kg', 'dob': '1989-07-19', 'birth_place': 'Araxá, Brazil', 'national_team': 'Brazilbr', 'club': 'Arsenal', 'wages': '￡ 50,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/a9dc785c_2022.jpg'}, {'Name': 'Josh Nichols', 'position': 'DF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-07-26', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/

In [878]:
fixtures_2024 = get_fixtures('https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures')
fixtures_df = pd.read_html(str(fixtures_2024))[0]
fixtures_df = fixtures_df.rename(columns={'Wk':'GW'})
fixtures_df = fixtures_df[~fixtures_df['GW'].isnull()]
fixtures_df['GW'] = "GW"+fixtures_df['GW'].astype(int).astype(str)

/var/folders/78/b2j3spl172n6y7p_sw2jggr40000gn/T/ipykernel_54417/760373454.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  fixtures_df = pd.read_html(str(fixtures_2024))[0]

In [990]:
fixtures_df[['Home_Score', 'Away_Score']] = fixtures_df['Score'].str.split('–', expand=True)

In [882]:
fixtures_df.to_csv('fixtures.csv')