In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [23]:
fbref_url = "https://fbref.com{}"
premier_league = fbref_url.format("/en/comps/9/Premier-League-Stats")
data = requests.get(premier_league)

## Retrieving Individual Player Data

In [796]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
import pickle
from IPython.display import clear_output


def make_request(endpoint: str) -> str:
    while True:
        response = requests.get(endpoint)
        if response.status_code == 429:  # Rate limited
            print("Rate limited. Pausing for 5 minutes...")
            print(endpoint)
            print(response.text)
            time.sleep(300)  # Wait for 5 minutes
        else:
            return response.text

def get_page_soup(url:str) -> BeautifulSoup:
    return BeautifulSoup(make_request(url), 'html.parser')

def extract_team_links(url:str) -> dict:
    league_teams_soup = get_page_soup(url)
    league_table = league_teams_soup.select('table.stats_table')[0]
    teams_dict = {team_link.get_text():fbref_url.format(team_link.get("href")) for team_link in league_table.find_all('a') if "squads" in team_link.get("href")}
    return teams_dict

def extract_player_links(url:str) -> dict:
    team_soup = get_page_soup(url)
    team_players_table = team_soup.select('table.stats_table')[0]
    players_links_dict = {
            l.get_text():fbref_url.format(l.get("href")) for l in team_players_table.find_all('a') 
            if (link := l.get("href")) and "players" in link and "matchlogs" not in link
        }
    return players_links_dict

def extract_player_details(url:str) -> dict:
    player_soup = get_page_soup(url)
    media_item_div = player_soup.select_one('div.media-item')
    image_src = media_item_div.find('img')['src'] if media_item_div else None

    # Extracting data dynamically
    for p in player_soup.find_all('p'):
        text = p.get_text(strip=True)
        # Extract position and footed
        if "Position:" in text:
            position_part = text.split("▪")[0].strip()
            footed_part = text.split("▪")[1].strip() if "▪" in text else None
            player_data['position'] = position_part.split(":")[1].strip()
            if footed_part:
                player_data['footed'] = footed_part.split(":")[1].strip()
        # Extract height and weight
        if "cm" in text and "kg" in text:
            height, weight = map(str.strip, text.split(',')[:2])
            player_data['height'] = height
            player_data['weight'] = weight.split('(')[0]
        # Extract date of birth and place of birth
        if "Born:" in text:
            birth_data = p.find("span", {"data-birth": True})
            if birth_data:
                player_data['dob'] = birth_data["data-birth"]
                birth_place = birth_data.find_next_sibling("span")
                if birth_place:
                    player_data['birth_place'] = birth_place.get_text(strip=True)[3:]  # Clean prefix if necessary
        # Extract national team
        if "National Team:" in text:
            player_data['national_team'] = text.split(":")[1].strip()
        # Extract club
        if "Club:" in text:
            player_data['club'] = text.split(":")[1].strip()
        # Extract wages and contract expiry
        if "Wages" in text:
            wages = p.select_one('.important').get_text(strip=True) if p.select_one('.important') else None
            player_data['wages'] = wages
            if "Expires" in text:
                contract_expires = text.split("Expires")[1].split(".")[0].strip()
                player_data['contract_expiry'] = contract_expires
    if image_src:
        player_data['img'] = image_src
    return player_data

# URLs
premier_league_links = [
    'https://fbref.com/en/comps/9/Premier-League-Stats',
    'https://fbref.com/en/comps/9/2023-2024/2023-2024-Premier-League-Stats',
    'https://fbref.com/en/comps/9/2022-2023/2022-2023-Premier-League-Stats',
    'https://fbref.com/en/comps/9/2021-2022/2021-t2022-Premier-League-Stats'
]

fbref_url = 'https://fbref.com{}'

# Load existing player list from CSV

all_players_dict = pd.read_csv('players.csv', index_col=0).to_dict(orient='index')

for premier_league_link in premier_league_links:
    # Fetch Premier League standings
    premier_league_year = premier_league_link.split('/')[-2]
    team_links = extract_team_links(premier_league_link)
    team_dict = {}
    for team_name, team_link in team_links.items():
        player_links = extract_player_links(team_link)
        team_players_dict = {}
        for player_name, player_link in player_links.items():
            if player_name in all_players_dict:
                print(f"{player_name} already in list. Skipping...")
                team_players_dict[player_name] = all_players_dict[player_name]
            else:
                player_data = extract_player_details(player_link)    
                team_players_dict[player_name] = player_data
                print(f"Retrieved player data from fbref {player_name}: {player_data}")
                all_players_dict[player_name] = player_data
                time.sleep(4)  
            
        clear_output(wait=True)
        team_dict[team_name] = team_players_dict
        print(squad_players_dict)
        time.sleep(5)
        clear_output(wait=True)
    pd.DataFrame.from_dict(all_players_dict).to_csv(f'players{premier_league_year }.csv', index=False)
    with open(f'team_dict_{premier_league_year}.pkl', 'wb') as f:
        pickle.dump(team_dict, f)

    print(f"Finished processing season: {premier_league_link.split('/')[-2]}")
    time.sleep(60)

Finished processing season: 9

KeyboardInterrupt:

## Get All Matches

In [885]:
import io

def get_fixtures(url:str) -> BeautifulSoup:
    fixtures_soup = get_page_soup(url)
    fixtures_table = fixtures_soup.find(id='all_sched')
    return fixtures_table

def get_match_data(url:str) -> list:
    game_soup = get_page_soup(url)
    team_stats = list()
    team_game_stats = game_soup.find_all(id=re.compile("all_player_stats"))
    goaly_game_stats = game_soup.find_all(id=re.compile("keeper_stats"), class_ = "table_wrapper")
    for team_stat in team_game_stats:
        team_stats.append(pd.read_html(str(team_stat))[0])
    for count, goaly_stat in enumerate(goaly_game_stats):
        goaly_df = pd.read_html(str(goaly_stat))[0]
        team_stats[count] = [team_stats[count], goaly_df]
    return team_stats


matches_dict = dict()

# quick ovveride:
premier_league_links = ['https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures']
for premiere_league_link in premier_league_links:
    premier_league_year = premier_league_link.split('/')[-2]
    fixtures = get_fixtures(premiere_league_link)
    match_report_links = [fbref_url.format(l.get('href')) for l in fixtures_table.find_all('a') if "Match Report" in l]
    print('LENGTH OF MATCH REPORT LINKS IS: '+str(len(match_report_links)))
    match_reports = list()
    
    for count, match_link  in enumerate(match_report_links):
        print(f"getting match data for match: {link}. Progress: {((count+1)/len(match_report_links))*100}%")
        match_data = get_match_data(match_link)
        match_reports.append(match_data)
        time.sleep(4)
        clear_output()
    matches_dict[premier_league_year] = match_reports

In [865]:
game_stats = matches_dict['9']
with open('game_stats.pkl', "wb") as f:
    pkl.dump(game_stats,f)

In [871]:
game_stats[189][0][0]

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
               Player                  #             Nation
0     Dominic Solanke               19.0            eng ENG
1         Timo Werner               16.0             de GER
2       Son Heung-min                7.0             kr KOR
3     Brennan Johnson               22.0            wls WAL
4    Dejan Kulusevski               21.0             se SWE
5     Pape Matar Sarr               29.0             sn SEN
6       Yves Bissouma                8.0             ml MLI
7      Lucas Bergvall               15.0             se SWE
8      James Maddison               10.0            eng ENG
9         Djed Spence               24.0            eng ENG
10        Archie Gray               14.0            eng ENG
11      Radu Drăgușin                6.0             ro ROU
12    Sergio Reguilón                3.0             es ESP
13        Pedro Porro               23.0             es ESP
14     Brandon Austin               40.0            eng ENG
15         15 Players                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Performance      \
                  Pos                Age                Min         Gls Ast
0                  FW             27-112                 90           1   0
1                  LW             28-304                 61           0   0
2                  LW             32-180                 29           0   0
3                  RW             23-226                 90           0   0
4               AM,RM             24-254                 90           0   0
5                  DM             22-112                 61           0   0
6                  CM             28-127                 29           0   0
7                  DM             18-337                 61           0   0
8                  LM             28-042                 29           0   0
9               CB,LB             24-148                 90           0   0
10                 CB             18-298                 90           0   0
11                 CB             22-336                 45           0   0
12                 LB             28-019                 45           0   0
13                 RB             25-113                 90           0   1
14                 GK             25-362                 90           0   0
15                NaN                NaN                990           1   1

             ... SCA     Passes                 Carries      Take-Ons
   PK PKatt  ... SCA GCA    Cmp  Att  Cmp% PrgP Carries PrgC      Att Succ
0   0     0  ...   2   0      9   17  52.9    1      15    1        2    0
1   0     0  ...   0   0     11   16  68.8    3      11    3        1    0
2   0     0  ...   2   0     24   27  88.9    2      24    2        4    1
3   0     0  ...   5   1     17   22  77.3    3      19    3        2    1
4   0     0  ...   5   0     28   38  73.7    7      38    5        1    1
5   0     0  ...   2   0     27   33  81.8    4      23    0        1    0
6   0     0  ...   0   0     29   30  96.7    4      22    2        0    0
7   0     0  ...   0   0     29   36  80.6    3      27    3        3    1
8   0     0  ...   1   0     31   35  88.6    7      30    2        0    0
9   0     0  ...   0   0     46   61  75.4    4      40    0        2    0
10  0     0  ...   0   0     46   53  86.8    2      36    0        0    0
11  0     0  ...   0   0      9   16  56.3    0      13    0        0    0
12  0     0  ...   0   0     30   41  73.2    4      28    0        2    1
13  0     0  ...   5   1     39   55  70.9    2      33    2        0    0
14  0     0  ...   0   0     22   32  68.8    0      22    0        0    0
15  0     0  ...  22   2    397  512  77.5   46     381   23       18    5

[16 rows x 31 columns]

In [875]:
x = get_fixtures('https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures')

In [877]:
pd.read_html(str(x))[0]

/var/folders/78/b2j3spl172n6y7p_sw2jggr40000gn/T/ipykernel_54417/126797153.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(str(x))[0]

,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes
0,1.0,Fri,2024-08-16,20:00,Manchester Utd,2.4,1–0,0.4,Fulham,73297.0,Old Trafford,Robert Jones,Match Report,NaN
1,1.0,Sat,2024-08-17,12:30,Ipswich Town,0.5,0–2,2.6,Liverpool,30014.0,Portman Road Stadium,Tim Robinson,Match Report,NaN
2,1.0,Sat,2024-08-17,15:00,Newcastle Utd,0.3,1–0,1.8,Southampton,52196.0,St James' Park,Craig Pawson,Match Report,NaN
3,1.0,Sat,2024-08-17,15:00,Nott'ham Forest,1.3,1–1,1.2,Bournemouth,29763.0,The City Ground,Michael Oliver,Match Report,NaN
4,1.0,Sat,2024-08-17,15:00,Everton,0.5,0–3,1.4,Brighton,39217.0,Goodison Park,Simon Hooper,Match Report,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,38.0,Sun,2025-05-25,16:00,Fulham,NaN,NaN,NaN,Manchester City,NaN,Craven Cottage,NaN,Head-to-Head,NaN
414,38.0,Sun,2025-05-25,16:00,Nott'ham Forest,NaN,NaN,NaN,Chelsea,NaN,The City Ground,NaN,Head-to-Head,NaN
415,38.0,Sun,2025-05-25,16:00,Manchester Utd,NaN,NaN,NaN,Aston Villa,NaN,Old Trafford,NaN,Head-to-Head,NaN
416,38.0,Sun,2025-05-25,16:00,Wolves,NaN,NaN,NaN,Brentford,NaN,Molineux Stadium,NaN,Head-to-Head,NaN
417,38.0,Sun,2025-05-25,16:00,Tottenham,NaN,NaN,NaN,Brighton,NaN,Tottenham Hotspur Stadium,NaN,Head-to-Head,NaN

In [804]:
from neo4j import GraphDatabase
from neo4j.exceptions import ServiceUnavailable
import logging
import pandas as pd

NEO4J_URI='neo4j+s://2b521897.databases.neo4j.io'
NEO4J_USERNAME='neo4j'
NEO4J_PASSWORD='nCUihZktDGHjJUpQtKUal0IJhrk0eSuMdSFUm99Th3Q'
AURA_INSTANCEID='2b521897'
AURA_INSTANCENAME='Instance01'

In [803]:
driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD))

In [677]:
# players_df = pd.read_csv('all_players_pd.csv')
print(players_data)

[{'Name': 'Virgil van Dijk', 'position': 'DF (CB, left)', 'footed': 'Right', 'height': '193cm', 'weight': '87kg', 'dob': '1991-07-08', 'birth_place': 'Breda, Netherlands', 'national_team': 'Netherlandsnl', 'club': 'Liverpool', 'wages': '￡ 220,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/e06683ca_2022.jpg'}, {'Name': 'Mohamed Salah', 'position': 'FW-MF (AM-WM, right)', 'footed': 'Left', 'height': '175cm', 'weight': '71kg', 'dob': '1992-06-15', 'birth_place': 'Basyūn, Egypt', 'national_team': 'Egypteg', 'club': 'Liverpool', 'wages': '￡ 350,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/e342ad68_2022.jpg'}, {'Name': 'Ryan Gravenberch', 'position': 'MF (CM-DM-WM)', 'footed': 'Right', 'height': '190cm', 'weight': '78kg', 'dob': '2002-05-16', 'birth_place': 'Amsterdam, Netherlands', 'national_team': 'Netherlandsnl', 'club': 'Liverpool', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/b8e740fb_2022.jpg'}, {'Name': 'Trent Alexander-Arnold', 'position': 'DF (FB, right)', 'footed': 'Right', 'height': '175cm', 'weight': '68kg', 'dob': '1998-10-07', 'birth_place': 'Liverpool, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': '￡ 180,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/cd1acf9d_2022.jpg'}, {'Name': 'Andrew Robertson', 'position': 'DF-MF (FB, left)', 'footed': 'Left', 'height': '178cm', 'weight': '63kg', 'dob': '1994-03-11', 'birth_place': 'Glasgow, Scotland, United Kingdom', 'national_team': 'Scotlandsct', 'club': 'Liverpool', 'wages': '￡ 160,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/2e4f5f03_2022.jpg'}, {'Name': 'Alexis Mac Allister', 'position': 'MF (AM-CM-DM-WM)', 'footed': 'Right', 'height': '174cm', 'weight': '72kg', 'dob': '1998-12-24', 'birth_place': 'Santa Rosa, Argentina', 'national_team': 'Argentinaar', 'club': 'Liverpool', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/83d074ff_2022.jpg'}, {'Name': 'Luis Díaz', 'position': 'FW-MF (AM-WM, left)', 'footed': 'Right', 'height': '180cm', 'weight': '72kg', 'dob': '1997-01-13', 'birth_place': 'Barrancas, Colombia', 'national_team': 'Colombiaco', 'club': 'Liverpool', 'wages': '￡ 55,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/4a1a9578_2022.jpg'}, {'Name': 'Dominik Szoboszlai', 'position': 'FW-MF (AM-CM-WM)', 'footed': 'Right', 'height': '186cm', 'weight': '73kg', 'dob': '2000-10-25', 'birth_place': 'Hungary', 'national_team': 'Hungaryhu', 'club': 'Liverpool', 'wages': '￡ 120,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/934e1968_2022.jpg'}, {'Name': 'Ibrahima Konaté', 'position': 'DF (CB, right)', 'footed': 'Right', 'height': '193cm', 'weight': '83kg', 'dob': '1999-05-25', 'birth_place': 'Paris, France', 'national_team': 'Francefr', 'club': 'Liverpool', 'wages': '￡ 70,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/5ed9b537_2022.jpg'}, {'Name': 'Cody Gakpo', 'position': 'FW-MF (AM)', 'footed': 'Right', 'height': '187cm', 'weight': '78kg', 'dob': '1999-05-07', 'birth_place': 'Gemeente Eindhoven, Netherlands', 'national_team': 'Netherlandsnl', 'club': 'Liverpool', 'wages': '￡ 120,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/1971591f_2022.jpg'}, {'Name': 'Alisson', 'position': 'GK', 'footed': 'Right', 'height': '193cm', 'weight': '91kg', 'dob': '1992-10-02', 'birth_place': 'Novo Hamburgo, Brazil', 'national_team': 'Brazilbr', 'club': 'Liverpool', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/7a2e46a8_2022.jpg'}, {'Name': 'Curtis Jones', 'position': 'FW-MF (CM-WM)', 'footed': 'Right', 'height': '185cm', 'weight': '72kg', 'dob': '2001-01-30', 'birth_place': 'Liverpool, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': '￡ 15,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/4fb9c88f_2022.jpg'}, {'Name': 'Caoimhín Kelleher', 'position': 'GK', 'footed': 'Right', 'height': '188cm', 'weight': '81kg', 'dob': '1998-11-23', 'birth_place': 'Cork, Republic of Ireland', 'national_team': 'Republic of Irelandie', 'club': 'Liverpool', 'wages': '￡ 10,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/62d7ef38_2022.jpg'}, {'Name': 'Darwin Núñez', 'position': 'FW', 'footed': 'Right', 'height': '187cm', 'weight': '79kg', 'dob': '1999-06-24', 'birth_place': 'Artigas, Uruguay', 'national_team': 'Uruguayuy', 'club': 'Liverpool', 'wages': '￡ 140,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/4d77b365_2022.jpg'}, {'Name': 'Diogo Jota', 'position': 'FW-MF', 'footed': 'Right', 'height': '178cm', 'weight': '69kg', 'dob': '1996-12-04', 'birth_place': 'Massarelos, Portugal', 'national_team': 'Portugalpt', 'club': 'Liverpool', 'wages': '￡ 140,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/178ae8f8_2022.jpg'}, {'Name': 'Joe Gomez', 'position': 'DF (CB-FB, right)', 'footed': 'Right', 'height': '188cm', 'weight': '77kg', 'dob': '1997-05-23', 'birth_place': 'Catford, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': '￡ 85,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/7a11550b_2022.jpg'}, {'Name': 'Kostas Tsimikas', 'position': 'DF (FB, left)', 'footed': 'Left', 'height': '177cm', 'weight': '69kg', 'dob': '1996-05-12', 'birth_place': 'Dimos Thessaloniki, Greece', 'national_team': 'Greecegr', 'club': 'Liverpool', 'wages': '￡ 75,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/f315ca93_2022.jpg'}, {'Name': 'Jarell Quansah', 'position': 'DF (CB)', 'footed': nan, 'height': '197cm', 'weight': '79kg', 'dob': '2003-01-29', 'birth_place': 'Warrington, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/4125cb98_2022.jpg'}, {'Name': 'Conor Bradley', 'position': 'DF-MF (FB, right)', 'footed': 'Right', 'height': '181cm', 'weight': '68kg', 'dob': '2003-07-09', 'birth_place': 'Northern Ireland, United Kingdom', 'national_team': 'Northern Irelandnir', 'club': 'Liverpool', 'wages': '￡ 10,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/bbd67769_2022.jpg'}, {'Name': 'Wataru Endo', 'position': 'DF-MF (CM-DM)', 'footed': 'Right', 'height': '178cm', 'weight': '74kg', 'dob': '1993-02-09', 'birth_place': 'Yokohama Shi, Japan', 'national_team': 'Japanjp', 'club': 'Liverpool', 'wages': '￡ 50,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/c149016b_2022.jpg'}, {'Name': 'Harvey Elliott', 'position': 'FW-MF (WM, right)', 'footed': 'Left', 'height': '170cm', 'weight': '67kg', 'dob': '2003-04-04', 'birth_place': 'Chertsey, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': '￡ 40,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/c8387671_2022.jpg'}, {'Name': 'Federico Chiesa', 'position': 'DF-FW-MF (WM)', 'footed': 'Right', 'height': '175cm', 'weight': '69kg', 'dob': '1997-10-25', 'birth_place': 'Genoa, Italy', 'national_team': 'Italyit', 'club': 'Liverpool', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/b0f7e36c_2022.jpg'}, {'Name': 'Vitezslav Jaros', 'position': 'GK', 'footed': 'Right', 'height': '184cm', 'weight': '69kg', 'dob': '2001-07-23', 'birth_place': 'Příbram, Czech Republic', 'national_team': 'Czech Republiccz', 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/12bb4d6a_2022.jpg'}, {'Name': 'Jayden Danns', 'position': 'FW', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-01-16', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': nan}, {'Name': 'Harvey Davies', 'position': 'GK', 'footed': nan, 'height': '186cm', 'weight': '77kg', 'dob': '2003-09-03', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/fd08a24b_2022.jpg'}, {'Name': 'James McConnell', 'position': 'MF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2004-09-13', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': nan}, {'Name': 'Tyler Morton', 'position': 'MF (CM-DM)', 'footed': 'Right', 'height': '178cm', 'weight': '67kg', 'dob': '2002-10-31', 'birth_place': 'England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/2bc28bb9_2022.jpg'}, {'Name': 'Amara Nallo', 'position': 'DF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-11-18', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': nan}, {'Name': 'Trey Nyoni', 'position': 'MF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2007-06-30', 'birth_place': 'England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Liverpool', 'wages': nan, 'contract_expiry': nan, 'img': nan}, {'Name': 'David Raya', 'position': 'GK', 'footed': 'Right', 'height': '186cm', 'weight': '81kg', 'dob': '1995-09-15', 'birth_place': 'Barcelona, Spain', 'national_team': 'Spaines', 'club': 'Arsenal', 'wages': '￡ 100,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/98ea5115_2022.jpg'}, {'Name': 'William Saliba', 'position': 'DF (CB, right)', 'footed': 'Right', 'height': '193cm', 'weight': '76kg', 'dob': '2001-03-24', 'birth_place': 'Bondy, France', 'national_team': 'Francefr', 'club': 'Arsenal', 'wages': '￡ 190,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/972aeb2a_2022.jpg'}, {'Name': 'Gabriel Magalhães', 'position': 'DF (CB, left)', 'footed': 'Left', 'height': '190cm', 'weight': '78kg', 'dob': '1997-12-19', 'birth_place': 'São Paulo, Brazil', 'national_team': 'Brazilbr', 'club': 'Arsenal', 'wages': '￡ 100,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/67ac5bb8_2022.jpg'}, {'Name': 'Kai Havertz', 'position': 'FW-MF (AM-CM-WM)', 'footed': 'Left', 'height': '186cm', 'weight': '77kg', 'dob': '1999-06-11', 'birth_place': 'Aachen, Germany', 'national_team': 'Germanyde', 'club': 'Arsenal', 'wages': '￡ 280,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/fed7cb61_2022.jpg'}, {'Name': 'Thomas Partey', 'position': 'DF-MF (CM-DM)', 'footed': 'Right', 'height': '185cm', 'weight': '78kg', 'dob': '1993-06-13', 'birth_place': 'Odumase Krobo, Ghana', 'national_team': 'Ghanagh', 'club': 'Arsenal', 'wages': '￡ 200,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/529f49ab_2022.jpg'}, {'Name': 'Jurriën Timber', 'position': 'DF (CB, right)', 'footed': 'Right', 'height': '179cm', 'weight': '78kg', 'dob': '2001-06-17', 'birth_place': 'Utrecht, Netherlands', 'national_team': 'Netherlandsnl', 'club': 'Arsenal', 'wages': '￡ 90,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/41034650_2022.jpg'}, {'Name': 'Declan Rice', 'position': 'DF-MF (CM-DM)', 'footed': 'Right', 'height': '185cm', 'weight': '77kg', 'dob': '1999-01-14', 'birth_place': 'London, England, United Kingdom', 'national_team': 'EnglandengOther', 'club': 'Arsenal', 'wages': '￡ 240,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/1c7012b8_2022.jpg'}, {'Name': 'Bukayo Saka', 'position': 'DF-FW-MF (AM, right)', 'footed': 'Left', 'height': '178cm', 'weight': '64kg', 'dob': '2001-09-05', 'birth_place': 'Ealing, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Arsenal', 'wages': '￡ 195,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/bc7dc64d_2022.jpg'}, {'Name': 'Gabriel Martinelli', 'position': 'FW-MF', 'footed': 'Right', 'height': '180cm', 'weight': '74kg', 'dob': '2001-06-18', 'birth_place': 'Guarulhos, Brazil', 'national_team': 'Brazilbr', 'club': 'Arsenal', 'wages': '￡ 180,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/48a5a5d6_2022.jpg'}, {'Name': 'Leandro Trossard', 'position': 'FW-MF (AM)', 'footed': 'Right', 'height': '172cm', 'weight': '60kg', 'dob': '1994-12-04', 'birth_place': 'Maasmechelen, Belgium', 'national_team': 'Belgiumbe', 'club': 'Arsenal', 'wages': '￡ 90,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/38ceb24a_2022.jpg'}, {'Name': 'Martin Ødegaard', 'position': 'FW-MF (AM-CM-WM)', 'footed': 'Left', 'height': '179cm', 'weight': '68kg', 'dob': '1998-12-17', 'birth_place': 'Drammen, Norway', 'national_team': 'Norwayno', 'club': 'Arsenal', 'wages': '￡ 240,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/79300479_2022.jpg'}, {'Name': 'Riccardo Calafiori', 'position': 'DF', 'footed': 'Left', 'height': '183cm', 'weight': '74kg', 'dob': '2002-05-19', 'birth_place': 'Roma, Italy', 'national_team': 'Italyit', 'club': 'Arsenal', 'wages': '￡ 120,000 Weekly', 'contract_expiry': 'June 2029', 'img': 'https://fbref.com/req/202302030/images/headshots/aded8e6f_2022.jpg'}, {'Name': 'Ben White', 'position': 'DF (CB-FB, right)', 'footed': 'Right', 'height': '182cm', 'weight': '73kg', 'dob': '1997-10-08', 'birth_place': 'Poole, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Arsenal', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/35e413f1_2022.jpg'}, {'Name': 'Mikel Merino', 'position': 'MF (AM-CM-DM-WM)', 'footed': 'Left', 'height': '188cm', 'weight': '78kg', 'dob': '1996-06-22', 'birth_place': 'Pamplona, Spain', 'national_team': 'Spaines', 'club': 'Arsenal', 'wages': '￡ 130,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/d080ed5e_2022.jpg'}, {'Name': 'Gabriel Jesus', 'position': 'FW-MF', 'footed': 'Right', 'height': '177cm', 'weight': '72kg', 'dob': '1997-04-03', 'birth_place': 'São Paulo, Brazil', 'national_team': 'Brazilbr', 'club': 'Arsenal', 'wages': '￡ 265,000 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/b66315ae_2022.jpg'}, {'Name': 'Jorginho', 'position': 'MF (CM-DM)', 'footed': 'Right', 'height': '180cm', 'weight': '64kg', 'dob': '1991-12-20', 'birth_place': 'Imbituba, Brazil', 'national_team': 'ItalyitOther', 'club': 'Arsenal', 'wages': '￡ 110,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/45db685d_2022.jpg'}, {'Name': 'Myles Lewis-Skelly', 'position': 'MF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-09-26', 'birth_place': 'England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/5dff6c28_2022.jpg'}, {'Name': 'Jakub Kiwior', 'position': 'DF-MF', 'footed': 'Left', 'height': '182cm', 'weight': '78kg', 'dob': '2000-02-15', 'birth_place': 'Tychy, Poland', 'national_team': 'Polandpl', 'club': 'Arsenal', 'wages': '￡ 58,000 Weekly', 'contract_expiry': 'June 2028', 'img': 'https://fbref.com/req/202302030/images/headshots/dc3e663e_2022.jpg'}, {'Name': 'Ethan Nwaneri', 'position': 'MF', 'footed': nan, 'height': '180cm', 'weight': '82kg', 'dob': '2007-03-21', 'birth_place': 'England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/7f94982c_2022.jpg'}, {'Name': 'Oleksandr Zinchenko', 'position': 'DF-MF (FB, left)', 'footed': 'Left', 'height': '175cm', 'weight': '60kg', 'dob': '1996-12-15', 'birth_place': 'Radomyshl, Ukraine', 'national_team': 'Ukraineua', 'club': 'Arsenal', 'wages': '￡ 150,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/51cf8561_2022.jpg'}, {'Name': 'Raheem Sterling', 'position': 'FW-MF (AM-WM)', 'footed': 'Right', 'height': '170cm', 'weight': '69kg', 'dob': '1994-12-08', 'birth_place': 'Kingston, Jamaica', 'national_team': 'EnglandengOther', 'club': 'Arsenal', 'wages': '￡ 162,500 Weekly', 'contract_expiry': 'June 2027', 'img': 'https://fbref.com/req/202302030/images/headshots/b400bde0_2022.jpg'}, {'Name': 'Takehiro Tomiyasu', 'position': 'DF (CB-FB)', 'footed': 'Right', 'height': '185cm', 'weight': '78kg', 'dob': '1998-11-05', 'birth_place': 'Fukuoka, Japan', 'national_team': 'Japanjp', 'club': 'Arsenal', 'wages': '￡ 100,000 Weekly', 'contract_expiry': 'June 2026', 'img': 'https://fbref.com/req/202302030/images/headshots/b3af9be1_2022.jpg'}, {'Name': 'Reiss Nelson', 'position': 'FW-MF', 'footed': 'Right', 'height': '175cm', 'weight': '68kg', 'dob': '1999-12-10', 'birth_place': 'Elephant & Castle, England, United Kingdom', 'national_team': 'Englandeng', 'club': 'Fulham', 'wages': '￡ 100,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/c5bdb6e3_2022.jpg'}, {'Name': 'Nathan Butler-Oyedeji', 'position': 'FW', 'footed': 'Right', 'height': nan, 'weight': nan, 'dob': '2003-01-04', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/3a686640_2022.jpg'}, {'Name': 'Ayden Heaven', 'position': 'DF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-09-22', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/64e17fab_2022.jpg'}, {'Name': 'Ismeal Kabia', 'position': 'MF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2005-12-10', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/6b15cf32_2022.jpg'}, {'Name': 'Maldini Kacurri', 'position': 'DF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2005-10-04', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/headshots/7be4311f_2022.jpg'}, {'Name': 'Neto', 'position': 'GK', 'footed': 'Right', 'height': '193cm', 'weight': '83kg', 'dob': '1989-07-19', 'birth_place': 'Araxá, Brazil', 'national_team': 'Brazilbr', 'club': 'Arsenal', 'wages': '￡ 50,000 Weekly', 'contract_expiry': 'June 2025', 'img': 'https://fbref.com/req/202302030/images/headshots/a9dc785c_2022.jpg'}, {'Name': 'Josh Nichols', 'position': 'DF', 'footed': nan, 'height': nan, 'weight': nan, 'dob': '2006-07-26', 'birth_place': 'England, United Kingdom', 'national_team': nan, 'club': 'Arsenal', 'wages': nan, 'contract_expiry': nan, 'img': 'https://fbref.com/req/202302030/images/

In [878]:
fixtures_2024 = get_fixtures('https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures')
fixtures_df = pd.read_html(str(fixtures_2024))[0]
fixtures_df = fixtures_df.rename(columns={'Wk':'GW'})
fixtures_df = fixtures_df[~fixtures_df['GW'].isnull()]
fixtures_df['GW'] = "GW"+fixtures_df['GW'].astype(int).astype(str)

/var/folders/78/b2j3spl172n6y7p_sw2jggr40000gn/T/ipykernel_54417/760373454.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  fixtures_df = pd.read_html(str(fixtures_2024))[0]

In [990]:
fixtures_df[['Home_Score', 'Away_Score']] = fixtures_df['Score'].str.split('–', expand=True)

In [882]:
fixtures_df.to_csv('fixtures.csv')

In [839]:
match_reports[0][1][0]

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
               Player                  #             Nation
0       Rodrigo Muniz                9.0             br BRA
1        Raúl Jiménez                7.0             mx MEX
2          Alex Iwobi               17.0             ng NGA
3        Adama Traoré               11.0             es ESP
4        Harry Wilson                8.0            wls WAL
5    Emile Smith Rowe               32.0            eng ENG
6         Tom Cairney               10.0            sct SCO
7          Saša Lukić               20.0             rs SRB
8      Jay Stansfield               28.0            eng ENG
9     Andreas Pereira               18.0             br BRA
10      Harrison Reed                6.0            eng ENG
11   Antonee Robinson               33.0             us USA
12      Calvin Bassey                3.0             ng NGA
13          Issa Diop               31.0             fr FRA
14         Kenny Tete                2.0             nl NED
15         Bernd Leno                1.0             de GER
16         16 Players                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Performance      \
                  Pos                Age                Min         Gls Ast
0                  FW             23-104                 77           0   0
1                  FW             33-103                 13           0   0
2                  LW             28-105                 90           0   0
3                  RW             28-204                 77           0   0
4                  RW             27-147                 13           0   0
5                  AM             24-019                 63           0   0
6               DM,AM             33-209                 27           0   0
7                  DM             28-003                 89           0   0
8               AM,DM             21-266                  1           0   0
9               DM,AM             28-228                 89           0   0
10                 DM             29-202                  1           0   0
11                 LB             27-008                 90           0   0
12                 CB             24-229                 90           0   0
13                 CB             27-220                 90           0   0
14                 RB             28-312                 90           0   0
15                 GK             32-165                 90           0   0
16                NaN                NaN                990           0   0

             ... SCA     Passes                  Carries      Take-Ons
   PK PKatt  ... SCA GCA    Cmp  Att   Cmp% PrgP Carries PrgC      Att Succ
0   0     0  ...   2   0      5    6   83.3    1      11    0        1    1
1   0     0  ...   0   0      2    4   50.0    0       2    1        0    0
2   0     0  ...   0   0     19   29   65.5    2      31    1        5    1
3   0     0  ...   4   0     14   21   66.7    0      25    5        9    4
4   0     0  ...   0   0      5    6   83.3    0       6    1        0    0
5   0     0  ...   0   0     20   27   74.1    1      23    0        0    0
6   0     0  ...   1   0     15   17   88.2    4      14    2        3    2
7   0     0  ...   0   0     40   45   88.9    4      30    1        0    0
8   0     0  ...   0   0      0    0    NaN    0       0    0        0    0
9   0     0  ...   9   0     37   55   67.3    5      28    1        2    0
10  0     0  ...   0   0      1    1  100.0    0       1    0        0    0
11  0     0  ...   0   0     32   42   76.2    2      31    2        2    0
12  0     0  ...   1   0     57   62   91.9    5      51    1        0    0
13  0     0  ...   0   0     28   35   80.0    2      26    0        0    0
14  0     0  ...   2   0     24   32   75.0    2      22    2        0    0
15  0     0  ...   0   0     30   42   71.4    0      28    0        0    0
16  0     0  ...  19   0    329  424   77.6   28     329   17       22    8

[17 rows x 31 columns]

In [735]:
# 
# (LEAGUE: PremLeague24-25) -> GWs -> Match -> Has_Home/Away
# 
#

In [805]:
with driver.session(database="neo4j") as session:
    query = "CREATE (l:League {name: $name})"
    session.run(query, {"name":"PremierLegue24-25"})

In [808]:
team_players = dict()
player_details = list()
for team, players in team_dict.items():
    team_players[team] = list()
    for player in players.keys():
        team_players[team].append(player)
        players[player]['Name'] = player
        player_details.append(players[player])
    team_players[team] = current_team_players

In [809]:
with driver.session(database="neo4j") as session:
    query = """
            UNWIND $players AS player
            MERGE (p:Player {name: player.Name})
            SET p.position = player.position,
                p.footed = player.footed,
                p.height = player.height,
                p.weight = player.weight,
                p.dob = player.dob,
                p.birth_place = player.birth_place,
                p.national_team = player.national_team,
                p.club = player.club,
                p.wages = player.wages,
                p.contract_expiry = player.contract_expiry,
                p.img = player.img
    """
    
    session.run(query, players=player_details)

In [841]:
# clean up before sending
with open('match_reports.pkl','rb') as f:
    d = pkl.load(f)

In [886]:
len(match_reports)

199

In [887]:
fixtures_df

,GW,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes,Home_Score,Away_Score
0,GW1,Fri,2024-08-16,20:00,Manchester Utd,2.4,1–0,0.4,Fulham,73297.0,Old Trafford,Robert Jones,Match Report,NaN,None,None
1,GW1,Sat,2024-08-17,12:30,Ipswich Town,0.5,0–2,2.6,Liverpool,30014.0,Portman Road Stadium,Tim Robinson,Match Report,NaN,None,None
2,GW1,Sat,2024-08-17,15:00,Newcastle Utd,0.3,1–0,1.8,Southampton,52196.0,St James' Park,Craig Pawson,Match Report,NaN,None,None
3,GW1,Sat,2024-08-17,15:00,Nott'ham Forest,1.3,1–1,1.2,Bournemouth,29763.0,The City Ground,Michael Oliver,Match Report,NaN,None,None
4,GW1,Sat,2024-08-17,15:00,Everton,0.5,0–3,1.4,Brighton,39217.0,Goodison Park,Simon Hooper,Match Report,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,GW38,Sun,2025-05-25,16:00,Fulham,NaN,NaN,NaN,Manchester City,NaN,Craven Cottage,NaN,Head-to-Head,NaN,None,None
414,GW38,Sun,2025-05-25,16:00,Nott'ham Forest,NaN,NaN,NaN,Chelsea,NaN,The City Ground,NaN,Head-to-Head,NaN,None,None
415,GW38,Sun,2025-05-25,16:00,Manchester Utd,NaN,NaN,NaN,Aston Villa,NaN,Old Trafford,NaN,Head-to-Head,NaN,None,None
416,GW38,Sun,2025-05-25,16:00,Wolves,NaN,NaN,NaN,Brentford,NaN,Molineux Stadium,NaN,Head-to-Head,NaN,None,None
417,GW38,Sun,2025-05-25,16:00,Tottenham,NaN,NaN,NaN,Brighton,NaN,Tottenham Hotspur Stadium,NaN,Head-to-Head,NaN,None,None

In [902]:
fixtures_df.iloc[0]['Away']

'Fulham'

In [964]:
corrects = list()
for i in range(min(len(fixtures_df), len(match_reports))):

    home_team = fixtures_df.iloc[i]['Home']
    away_team = fixtures_df.iloc[i]['Away']

    home_team_player_team = all_players_dict[match_reports[i][0][0][('Unnamed: 0_level_0', 'Player')].iloc[0]]['club']
    away_team_player_team = all_players_dict[match_reports[i][1][0][('Unnamed: 0_level_0', 'Player')].iloc[0]]['club']

    if (home_team in home_team_player_team or home_team_player_team in home_team) and (away_team in away_team_player_team or away_team_player_team in away_team):
        continue
    else:
        
        print(fixtures_df.iloc[i])
        print(home_team)
        print(away_team)
        
        print(home_team_player_team)
        print(away_team_player_team)
        
        x = input('correct?')
        corrects.append(x)
        clear_output(wait=True)

In [927]:
players_team

{'Al Shabab (KSA)',
 'Anderlecht',
 'Arsenal',
 'Aston Villa',
 'Augsburg',
 'Auxerre',
 'Birmingham City',
 'Bournemouth',
 'Brentford',
 'Brighton & Hove Albion',
 'Burnley',
 'Chelsea',
 'Chesterfield',
 'Crystal Palace',
 'Derby County',
 'Everton',
 'Flamengo',
 'Fulham',
 'Hull City',
 'Ipswich Town',
 'Leicester City',
 'Liverpool',
 'Mallorca',
 'Manchester City',
 'Manchester United',
 'Marseille',
 'Middlesbrough',
 'Napoli',
 'Newcastle United',
 'Nottingham Forest',
 'Oxford United',
 'Portsmouth',
 'Queens Park Rangers',
 'Rennes',
 'Sevilla',
 'Southampton',
 'Stoke City',
 'Swansea City',
 'Tottenham Hotspur',
 'Werder Bremen',
 'West Bromwich Albion',
 'West Ham United',
 'Westerlo',
 'Wolverhampton Wanderers'}

In [965]:
# this is very important please do not delete
mappings = {"Brighton":'Brighton & Hove Albion',
            'Manchester Utd':'Manchester United',
            'Newcastle Utd':'Newcastle United',
            "Nott'ham Forest":'Nottingham Forest',
            'Tottenham':'Tottenham Hotspur',
            'West Ham':'West Ham United',
            'Wolves':'Wolverhampton Wanderers'}

In [935]:
for player, player_data in all_players_dict.items():
    club_name = player_data['club']  
    all_players_dict[player]['club'] = mappings[club_name] if club_name in mappings else club_name

In [960]:
fixtures_df = fixtures_df['Home'].map(mappings)
fixtures_df = fixtures_df['Away'].map(mappings)

In [951]:
fixtures_df = pd.read_csv('fixtures.csv')

In [984]:
fixtures_df.iloc[18]

Unnamed: 0                           19
GW                                  GW2
Day                                 Sun
Date                         2024-08-25
Time                              14:00
Home            Wolverhampton Wanderers
xG                                  1.9
Score                               2–6
xG.1                                1.6
Away                            Chelsea
Attendance                      31235.0
Venue                  Molineux Stadium
Referee                  Darren England
Match Report               Match Report
Notes                               NaN
Home_Score                          NaN
Away_Score                          NaN
Name: 18, dtype: object

In [1042]:
with driver.session(database="neo4j") as session:
    query = "match (n) detach delete n"
    session.run(query)

In [1043]:
with driver.session(database="neo4j") as session:
    query = "CREATE (l:League {name: $name})"
    session.run(query, {"name":"PremierLeague"})

    query = "CREATE (s:Season {name: $name})"
    session.run(query, {"name":"24-25"})

    query = """
        MATCH (s:Season{name:$season_name}), (l:League{name: $league_name}) 
        CREATE (s)-[:SEASON_OF_LEAGUE]->(l)
        """
    print(session.run(query, {"league_name": "PremierLeague", "season_name": "24-25"}))

<neo4j._sync.work.result.Result object at 0x7fbf0ca8e400>

In [1044]:
team_players = dict()
player_details = list()

for team, players in team_dict.items():
    team_players[team] = list()
    for player in players.keys():
        team_players[team].append(player)
        players[player]['Name'] = player
        players[player]['Team'] = team  # Fix the key access from player to players
        player_details.append(players[player])
    team_players[team] = team_players[team]

with driver.session(database="neo4j") as session:
    query = """
            UNWIND $players AS player
            MERGE (p:Player {name: player.Name})
            SET p.position = player.position,
                p.footed = player.footed,
                p.height = player.height,
                p.weight = player.weight,
                p.dob = player.dob,
                p.birth_place = player.birth_place,
                p.national_team = player.national_team,
                p.club = player.club,
                p.wages = player.wages,
                p.contract_expiry = player.contract_expiry,
                p.img = player.img

            MERGE (team:Team {name: player.Team})
            MERGE (p)-[:PLAYS_FOR]->(team)
    """
    
    session.run(query, players=player_details)

In [1028]:
player_details[0]

{'position': 'DF (CB, left)',
 'footed': 'Right',
 'height': '193cm',
 'weight': '87kg',
 'dob': '1991-07-08',
 'birth_place': 'Breda, Netherlands',
 'national_team': 'Netherlandsnl',
 'club': 'Liverpool',
 'wages': '￡ 220,000 Weekly',
 'contract_expiry': 'June 2025',
 'img': 'https://fbref.com/req/202302030/images/headshots/e06683ca_2022.jpg',
 'Name': 'Virgil van Dijk'}

In [1045]:
with driver.session(database="neo4j") as session:
    # Create GameWeek nodes and relationships
    for gw in range(1, 39):  # Loop from 1 to 38
        query = """
        MATCH (s:Season {name: $season_name})
        CREATE (gw:GameWeek {number: $number})-[:IS_A_GW]->(s)
        """
        session.run(query, {"season_name": "24-25", "number": gw})

In [1046]:
with driver.session(database="neo4j") as session:
    for _, row in fixtures_df.iterrows():
        query = """
        MERGE (match:Match {id: $match_id})
        SET match.date = $date,
            match.time = $time,
            match.home_team = $home_team,
            match.away_team = $away_team,
            match.home_expected = $home_expected,
            match.away_expected = $away_expected,
            match.home_score = $home_score,
            match.away_score = $away_score

        MERGE (ref:Referee {name: $referee})
        MERGE (venue:Venue {name: $venue})
        
        MERGE (home_team:Team {name: $home_team})
        MERGE (away_team:Team {name: $away_team})
        
        MERGE (match)-[:REFERRED_BY]->(ref)
        MERGE (match)-[:PLAYED_AT]->(venue)
        MERGE (match)-[:HOME_TEAM]->(home_team)
        MERGE (match)-[:AWAY_TEAM]->(away_team)
        """
        
        # Prepare the data dictionary
        data ={
            "match_id": f"GW{row['GW']}_{row['Home']}_vs_{row['Away']}",
            "date": row["Date"],
            "time": row["Time"],
            "home_team": row["Home"],
            "away_team": row["Away"],
        }
        if row["Match Report"]:
            data["home_expected"]= row["xG"],
            data["away_expected"]= row["xG.1"],
            data["home_score"]= row["Home_Score"],
            data["away_score"]= row["Away_Score"],
            data["referee"]= row["Referee"],
            data["venue"] =  row["Venue"]
        
        # Execute the query
        session.run(query, data)

In [1015]:
teams = pd.concat([fixtures_df["Home"],fixtures_df["Away"]]).unique().tolist()
with driver.session(database="neo4j") as session:
    for team_name in teams:
        query = "CREATE (t:Team {name: $name})"
        session.run(query, {"name":team_name})

In [1047]:
with driver.session(database="neo4j") as session:
    for i, row in fixtures_df[:len(match_reports)].iterrows():
        match_id = f"GW{row['GW']}_{row['Home']}_vs_{row['Away']}"
        home_team_name = row['Home']
        away_team_name = row['Away']

        # Add Home Team Player Stats
        for _, player_stats in home_team_stats.iterrows():
            player_query = """
            MERGE (player:Player {name: $player_name, nation: $nation, position: $position, age: $age})
            MERGE (team:Team {name: $team_name})
            MERGE (player)-[:PLAYS_FOR]->(team)
            MERGE (match:Match {id: $match_id})
            MERGE (match)-[h:HOME_TEAM_PLAYER_STATS]->(player)
            SET h.goals = $goals,
                h.assists = $assists,
                h.penalties = $penalties,
                h.shots = $shots,
                h.shots_on_target = $shots_on_target,
                h.touches = $touches,
                h.tackles = $tackles,
                h.interceptions = $interceptions,
                h.blocks = $blocks,
                h.xg = $xg,
                h.npxg = $npxg,
                h.xag = $xag,
                h.sca = $sca,
                h.gca = $gca,
                h.passes_completed = $passes_completed,
                h.passes_attempted = $passes_attempted,
                h.pass_accuracy = $pass_accuracy,
                h.progressive_passes = $progressive_passes,
                h.carries = $carries,
                h.progressive_carries = $progressive_carries
            """
            session.run(player_query, {
                "player_name": player_stats[('Unnamed: 0_level_0', 'Player')],
                "nation": player_stats[('Unnamed: 2_level_0', 'Nation')],
                "position": player_stats[('Unnamed: 3_level_0', 'Pos')],
                "age": player_stats[('Unnamed: 4_level_0', 'Age')],
                "match_id": match_id,
                "team_name": home_team_name,
                "goals": player_stats[('Performance', 'Gls')],
                "assists": player_stats[('Performance', 'Ast')],
                "penalties": player_stats[('Performance', 'PK')],
                "shots": player_stats[('Performance', 'Sh')],
                "shots_on_target": player_stats[('Performance', 'SoT')],
                "touches": player_stats[('Performance', 'Touches')],
                "tackles": player_stats[('Performance', 'Tkl')],
                "interceptions": player_stats[('Performance', 'Int')],
                "blocks": player_stats[('Performance', 'Blocks')],
                "xg": player_stats[('Expected', 'xG')],
                "npxg": player_stats[('Expected', 'npxG')],
                "xag": player_stats[('Expected', 'xAG')],
                "sca": player_stats[('SCA', 'SCA')],
                "gca": player_stats[('SCA', 'GCA')],
                "passes_completed": player_stats[('Passes', 'Cmp')],
                "passes_attempted": player_stats[('Passes', 'Att')],
                "pass_accuracy": player_stats[('Passes', 'Cmp%')],
                "progressive_passes": player_stats[('Passes', 'PrgP')],
                "carries": player_stats[('Carries', 'Carries')],
                "progressive_carries": player_stats[('Carries', 'PrgC')],
            })

        # Add Away Team Player Stats
        for _, player_stats in away_team_stats.iterrows():
            player_query = """
            MERGE (player:Player {name: $player_name, nation: $nation, position: $position, age: $age})
            MERGE (team:Team {name: $team_name})
            MERGE (player)-[:PLAYS_FOR]->(team)
            MERGE (match:Match {id: $match_id})
            MERGE (match)-[a:AWAY_TEAM_PLAYER_STATS]->(player)
            SET a.goals = $goals,
                a.assists = $assists,
                a.penalties = $penalties,
                a.shots = $shots,
                a.shots_on_target = $shots_on_target,
                a.touches = $touches,
                a.tackles = $tackles,
                a.interceptions = $interceptions,
                a.blocks = $blocks,
                a.xg = $xg,
                a.npxg = $npxg,
                a.xag = $xag,
                a.sca = $sca,
                a.gca = $gca,
                a.passes_completed = $passes_completed,
                a.passes_attempted = $passes_attempted,
                a.pass_accuracy = $pass_accuracy,
                a.progressive_passes = $progressive_passes,
                a.carries = $carries,
                a.progressive_carries = $progressive_carries
            """
            session.run(player_query, {
                "player_name": player_stats[('Unnamed: 0_level_0', 'Player')],
                "nation": player_stats[('Unnamed: 2_level_0', 'Nation')],
                "position": player_stats[('Unnamed: 3_level_0', 'Pos')],
                "age": player_stats[('Unnamed: 4_level_0', 'Age')],
                "match_id": match_id,
                "team_name": away_team_name,
                "goals": player_stats[('Performance', 'Gls')],
                "assists": player_stats[('Performance', 'Ast')],
                "penalties": player_stats[('Performance', 'PK')],
                "shots": player_stats[('Performance', 'Sh')],
                "shots_on_target": player_stats[('Performance', 'SoT')],
                "touches": player_stats[('Performance', 'Touches')],
                "tackles": player_stats[('Performance', 'Tkl')],
                "interceptions": player_stats[('Performance', 'Int')],
                "blocks": player_stats[('Performance', 'Blocks')],
                "xg": player_stats[('Expected', 'xG')],
                "npxg": player_stats[('Expected', 'npxG')],
                "xag": player_stats[('Expected', 'xAG')],
                "sca": player_stats[('SCA', 'SCA')],
                "gca": player_stats[('SCA', 'GCA')],
                "passes_completed": player_stats[('Passes', 'Cmp')],
                "passes_attempted": player_stats[('Passes', 'Att')],
                "pass_accuracy": player_stats[('Passes', 'Cmp%')],
                "progressive_passes": player_stats[('Passes', 'PrgP')],
                "carries": player_stats[('Carries', 'Carries')],
                "progressive_carries": player_stats[('Carries', 'PrgC')],
            })

         # Add Home Team Goalie Stats
        for _, goalie_stats in home_team_goaly_stats.iterrows():
            goalie_query = """
            MERGE (goalie:Player {name: $goalie_name, nation: $nation, position: "GK", age: $age})
            MERGE (team:Team {name: $team_name})
            MERGE (goalie)-[:PLAYS_FOR]->(team)
            MERGE (match:Match {id: $match_id})
            MERGE (match)-[:HOME_TEAM_GOALIE_STATS]->(goalie)
            SET goalie.minutes_played = $minutes_played,
                goalie.sota = $sota,
                goalie.goals_allowed = $goals_allowed,
                goalie.saves = $saves,
                goalie.save_percentage = $save_percentage,
                goalie.psxg = $psxg,
                goalie.passes_completed = $passes_completed,
                goalie.passes_attempted = $passes_attempted,
                goalie.pass_accuracy = $pass_accuracy,
                goalie.gk_passes_attempted = $gk_passes_attempted,
                goalie.throws = $throws,
                goalie.launch_percentage = $launch_percentage,
                goalie.launch_average_length = $launch_average_length,
                goalie.goal_kicks_attempted = $goal_kicks_attempted,
                goalie.goal_kick_launch_percentage = $goal_kick_launch_percentage,
                goalie.goal_kick_average_length = $goal_kick_average_length,
                goalie.crosses_opportunities = $crosses_opportunities,
                goalie.crosses_stops = $crosses_stops,
                goalie.crosses_stop_percentage = $crosses_stop_percentage,
                goalie.opa = $opa,
                goalie.opa_average_distance = $opa_average_distance
            """
            session.run(goalie_query, {
                "goalie_name": goalie_stats[('Unnamed: 0_level_0', 'Player')],
                "nation": goalie_stats[('Unnamed: 1_level_0', 'Nation')],
                "age": goalie_stats[('Unnamed: 2_level_0', 'Age')],
                "match_id": match_id,
                "team_name": home_team_name,
                "minutes_played": goalie_stats[('Unnamed: 3_level_0', 'Min')],
                "sota": goalie_stats[('Shot Stopping', 'SoTA')],
                "goals_allowed": goalie_stats[('Shot Stopping', 'GA')],
                "saves": goalie_stats[('Shot Stopping', 'Saves')],
                "save_percentage": goalie_stats[('Shot Stopping', 'Save%')],
                "psxg": goalie_stats[('Shot Stopping', 'PSxG')],
                "passes_completed": goalie_stats[('Launched', 'Cmp')],
                "passes_attempted": goalie_stats[('Launched', 'Att')],
                "pass_accuracy": goalie_stats[('Launched', 'Cmp%')],
                "gk_passes_attempted": goalie_stats[('Passes', 'Att (GK)')],
                "throws": goalie_stats[('Passes', 'Thr')],
                "launch_percentage": goalie_stats[('Passes', 'Launch%')],
                "launch_average_length": goalie_stats[('Passes', 'AvgLen')],
                "goal_kicks_attempted": goalie_stats[('Goal Kicks', 'Att')],
                "goal_kick_launch_percentage": goalie_stats[('Goal Kicks', 'Launch%')],
                "goal_kick_average_length": goalie_stats[('Goal Kicks', 'AvgLen')],
                "crosses_opportunities": goalie_stats[('Crosses', 'Opp')],
                "crosses_stops": goalie_stats[('Crosses', 'Stp')],
                "crosses_stop_percentage": goalie_stats[('Crosses', 'Stp%')],
                "opa": goalie_stats[('Sweeper', '#OPA')],
                "opa_average_distance": goalie_stats[('Sweeper', 'AvgDist')],
            })

        # Add Away Team Goalie Stats
        for _, goalie_stats in away_team_goaly_stats.iterrows():
            session.run(goalie_query, {
                "goalie_name": goalie_stats[('Unnamed: 0_level_0', 'Player')],
                "nation": goalie_stats[('Unnamed: 1_level_0', 'Nation')],
                "age": goalie_stats[('Unnamed: 2_level_0', 'Age')],
                "match_id": match_id,
                "team_name": away_team_name,
                "minutes_played": goalie_stats[('Unnamed: 3_level_0', 'Min')],
                "sota": goalie_stats[('Shot Stopping', 'SoTA')],
                "goals_allowed": goalie_stats[('Shot Stopping', 'GA')],
                "saves": goalie_stats[('Shot Stopping', 'Saves')],
                "save_percentage": goalie_stats[('Shot Stopping', 'Save%')],
                "psxg": goalie_stats[('Shot Stopping', 'PSxG')],
                "passes_completed": goalie_stats[('Launched', 'Cmp')],
                "passes_attempted": goalie_stats[('Launched', 'Att')],
                "pass_accuracy": goalie_stats[('Launched', 'Cmp%')],
                "gk_passes_attempted": goalie_stats[('Passes', 'Att (GK)')],
                "throws": goalie_stats[('Passes', 'Thr')],
                "launch_percentage": goalie_stats[('Passes', 'Launch%')],
                "launch_average_length": goalie_stats[('Passes', 'AvgLen')],
                "goal_kicks_attempted": goalie_stats[('Goal Kicks', 'Att')],
                "goal_kick_launch_percentage": goalie_stats[('Goal Kicks', 'Launch%')],
                "goal_kick_average_length": goalie_stats[('Goal Kicks', 'AvgLen')],
                "crosses_opportunities": goalie_stats[('Crosses', 'Opp')],
                "crosses_stops": goalie_stats[('Crosses', 'Stp')],
                "crosses_stop_percentage": goalie_stats[('Crosses', 'Stp%')],
                "opa": goalie_stats[('Sweeper', '#OPA')],
                "opa_average_distance": goalie_stats[('Sweeper', 'AvgDist')],
            })

In [1072]:
query = """
MATCH (player:Player)-[:PLAYS_FOR]->(team:Team)
WITH player, COUNT(team) AS teamCount
WHERE teamCount > 3
RETURN player, teamCount
"""
players_errors = list()
with driver.session(database="neo4j") as session:
    r = session.run(query)
    for record in r:
        players_errors.append(record["player"]["name"])

In [1101]:
player_to_find = players_errors[0]
for i in range(len(match_reports)):
    if player_to_find in match_reports[i][0][0][("Unnamed: 0_level_0","Player")].tolist():
        print(match_reports[i][0][0])
        print('----------------------------------')
    if player_to_find in match_reports[i][1][0][("Unnamed: 0_level_0","Player")].tolist():
        print(match_reports[i][1][0])
        print('----------------------------------')

    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Player                  #             Nation
0      Bruno Fernandes                8.0             pt POR
1      Marcus Rashford               10.0            eng ENG
2          Amad Diallo               16.0             ci CIV
3   Alejandro Garnacho               17.0             ar ARG
4          Mason Mount                7.0            eng ENG
5       Joshua Zirkzee               11.0             nl NED
6        Kobbie Mainoo               37.0            eng ENG
7      Scott McTominay               39.0            sct SCO
8             Casemiro               18.0             br BRA
9          Diogo Dalot               20.0             pt POR
10   Lisandro Martínez                6.0             ar ARG
11       Harry Maguire                5.0            eng ENG
12         Jonny Evans               35.0            nir NIR
13   Noussair Mazraoui                3.0             ma MAR
14    Matthijs de Ligt                4.0             nl NED
15         André Onana               24.0             cm CMR
16          16 Players                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Performance      \
                  Pos                Age                Min         Gls Ast
0               FW,AM             29-343                 90           0   0
1                  LW             26-290                 90           0   0
2                  RW             22-036                 60           0   0
3                  RW             20-046                 30           0   1
4                  AM             25-219                 60           0   0
5                  FW             23-086                 30           1   0
6                  DM             19-119                 83           0   0
7                  DM             27-252                  7           0   0
8                  DM             32-175                 90           0   0
9               LB,RB             25-151                 90           0   0
10              CB,LB             26-211                 90           0   0
11                 CB             31-164                 80           0   0
12                 CB             36-226                 10           0   0
13                 RB             26-276                 80           0   0
14                 CB             25-004                 10           0   0
15                 GK             28-136                 90           0   0
16                NaN                NaN                990           1   1

             ... SCA     Passes                  Carries      Take-Ons
   PK PKatt  ... SCA GCA    Cmp  Att   Cmp% PrgP Carries PrgC      Att Succ
0   0     0  ...   2   0     43   60   71.7    6      50    7        1    1
1   0     0  ...   1   0     22   30   73.3    2      34    2        6    0
2   0     0  ...   1   0     28   33   84.8    1      22    0        1    1
3   0     0  ...   3   1     10   11   90.9    0      11    2        2    0
4   0     0  ...   3   0     11   15   73.3    1      16    0        2    0
5   0     0  ...   1   0      8    9   88.9    1       6    0        0    0
6   0     0  ...   1   0     37   41   90.2    5      39    0        5    4
7   0     0  ...   0   0      4    4  100.0    0       3    0        0    0
8   0     0  ...   5   1     44   57   77.2    4      46    0        1    0
9   0     0  ...   1   0     49   60   81.7    3      40    1        1    1
10  0     0  ...   3   0     55   62   88.7    9      51    1        0    0
11  0     0  ...   2   0     50   60   83.3    8      40    1        2    1
12  0     0  ...   0   0      4    6   66.7    0       2    0        0    0
13  0     0  ...   0   0     41   45   91.1    3      34    1        0    0
14  0     0  ...   0   0      2    2  100.0    0       2    0        0    0
15  0     0  ...   1   0     22   29   75.9    0      24    0        0    0
16  0     0  ...  24   2    430  524   82.1   43     420   15       21    8

[17 rows x 31 columns]
----------------------------------
    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Player                  #             Nation
0      Bruno Fernandes                8.0             pt POR
1      Scott McTominay               39.0            sct SCO
2      Marcus Rashford               10.0            eng ENG
3   Alejandro Garnacho               17.0             ar ARG
4          Amad Diallo               16.0             ci CIV
5               Antony               21.0             br BRA
6          Mason Mount                7.0            eng ENG
7       Joshua Zirkzee               11.0             nl NED
8        Kobbie Mainoo               37.0            eng ENG
9             Casemiro               18.0             br BRA
10         Diogo Dalot               20.0             pt POR
11   Lisandro Martínez                6.0             ar ARG
12       Harry Maguire                5.0            eng ENG
13    Matthijs de Ligt                4.0             nl NED
14   Noussair Mazraoui                3.0             ma MAR
15         André Onana               24.0             cm CMR
16          16 Players                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Performance      \
                  Pos                Age                Min         Gls Ast
0               FW,AM             29-351                 78           0   0
1                  AM             27-260                 12           0   0
2               LW,FW             26-298                 64           0   0
3                  LW             20-054                 26           0   0
4                  RW             22-044                 89           1   0
5                  RW             24-182                  1           0   0
6                  AM             25-227                 45           0   0
7               FW,LW             23-094                 45           0   0
8                  DM             19-127                 90           0   0
9                  DM             32-183                 90           0   0
10                 LB             25-159                 90           0   0
11                 CB             26-219                 90           0   0
12                 CB             31-172                 78           0   0
13                 CB             25-012                 12           0   0
14                 RB             26-284                 90           0   1
15                 GK             28-144                 90           0   0
16                NaN                NaN                990           1   1

             ... SCA     Passes                  Carries      Take-Ons
   PK PKatt  ... SCA GCA    Cmp  Att   Cmp% PrgP Carries PrgC      Att Succ
0   0     0  ...   4   0     32   45   71.1    6      30    1        0    0
1   0     0  ...   1   0      6    6  100.0    1       7    0        1    0
2   0     0  ...   0   0     13   18   72.2    0      14    2        4    1
3   0     0  ...   1   0     11   16   68.8    2      19    3        3    1
4   0     0  ...   3   0     33   45   73.3    4      37    7        3    1
5   0     0  ...   1   0      1    2   50.0    0       1    0        0    0
6   0     0  ...   0   0     15   18   83.3    2      14    0        0    0
7   0     0  ...   1   0      7   10   70.0    0       6    0        3    2
8   0     0  ...   1   1     41   45   91.1    3      35    0        4    4
9   0     0  ...   2   0     44   54   81.5    2      35    0        0    0
10  0     0  ...   2   0     60   66   90.9    4      46    1        3    1
11  0     0  ...   1   0     70   73   95.9    4      66    0        0    0
12  0     0  ...   1   0     41   45   91.1    0      39    0        0    0
13  0     0  ...   0   0      8    8  100.0    1       5    0        0    0
14  0     0  ...   2   1     34   42   81.0    5      26    1        1    0
15  0     0  ...   1   0     54   59   91.5    0      53    0        0    0
16  0     0  ...  21   2    470  552   85.1   34     433   15       22   10

[17 rows x 31 columns]
----------------------------------
    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Player                  #             Nation
0       Joshua Zirkzee               11.0             nl NED
1    Christian Eriksen               14.0             dk DEN
2      Marcus Rashford               10.0            eng ENG
3   Alejandro Garnacho               17.0             ar ARG
4          Amad Diallo               16.0             ci CIV
5      Bruno Fernandes                8.0             pt POR
6        Kobbie Mainoo               37.0            eng ENG
7             Casemiro               18.0             br BRA
8         Toby Collyer               43.0            eng ENG
9          Diogo Dalot               20.0             pt POR
10   Lisandro Martínez                6.0             ar ARG
11    Matthijs de Ligt                4.0             nl NED
12       Harry Maguire                5.0            eng ENG
13   Noussair Mazraoui                3.0             ma MAR
14         André Onana               24.0             cm CMR
15          15 Players                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Performance      \
                  Pos                Age                Min         Gls Ast
0                  FW             23-102                 85           0   0
1                  AM             32-200                  5           0   0
2                  LW             26-306                 90           0   0
3                  RW             20-062                 68           0   0
4                  RW             22-052                 22           0   0
5               AM,FW             29-359                 90           0   0
6                  DM             19-135                 90           0   0
7                  DM             32-191                 45           0   0
8                  DM             20-242                 45           0   0
9                  LB             25-167                 90           0   0
10                 CB             26-227                 90           0   0
11                 CB             25-020                 68           0   0
12                 CB             31-180                 22           0   0
13                 RB             26-292                 90           0   0
14                 GK             28-152                 90           0   0
15                NaN                NaN                990           0   0

             ... SCA     Passes                 Carries      Take-Ons
   PK PKatt  ... SCA GCA    Cmp  Att  Cmp% PrgP Carries PrgC      Att Succ
0   0     0  ...   1   0     15   21  71.4    3      17    0        3    0
1   0     0  ...   0   0      3    4  75.0    0       3    0        0    0
2   0     0  ...   2   0     18   26  69.2    1      21    1        5    2
3   0     0  ...   1   0     20   24  83.3    0      19    3        3    0
4   0     0  ...   2   0     12   15  80.0    0      15    3        2    0
5   0     0  ...   2   0     38   49  77.6    5      36    0        1    0
6   0     0  ...   1   0     36   41  87.8    3      33    2        3    2
7   0     0  ...   0   0     26   37  70.3    3      26    1        1    1
8   0     0  ...   2   0     15   19  78.9    2      20    0        1    1
9   0     0  ...   2   0     45   57  78.9    7      28    1        2    1
10  0     0  ...   1   0     61   65  93.8    3      54    0        0    0
11  0     0  ...   0   0     47   55  85.5    1      43    0        0    0
12  0     0  ...   0   0     18   22  81.8    0      14    0        0    0
13  0     0  ...   2   0     53   66  80.3    5      39    1        1    1
14  0     0  ...   0   0     46   55  83.6    0      39    0        0    0
15  0     0  ...  16   0    453  556  81.5   33     407   12       22    8

[16 rows x 31 columns]
----------------------------------
       Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                   Player                  #             Nation
0          Joshua Zirkzee               11.0             nl NED
1         Marcus Rashford               10.0            eng ENG
2      Alejandro Garnacho               17.0             ar ARG
3             Amad Diallo               16.0             ci CIV
4         Bruno Fernandes                8.0             pt POR
5           Kobbie Mainoo               37.0            eng ENG
6       Christian Eriksen               14.0             dk DEN
7   Manuel Ugarte Ribeiro               25.0             uy URU
8             Diogo Dalot               20.0             pt POR
9       Lisandro Martínez                6.0             ar ARG
10            Jonny Evans               35.0            nir NIR
11       Matthijs de Ligt                4.0             nl NED
12               Casemiro               18.0             br BRA
13      Noussair Mazraoui                3.0             ma MAR
14          Harry Maguire                5.0            eng ENG
15            André Onana               24.0             cm CMR
16             16 Players                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Performance      \
                  Pos                Age                Min         Gls Ast
0                  FW             23-115                 90           0   0
1                  LW             26-319                 72           1   0
2                  LW             20-075                 18           1   0
3                  RW             22-065                 90           0   1
4                  AM             30-006                 90           0   1
5                  DM             19-148                 90           0   0
6                  DM             32-213                 72           0   0
7                  DM             23-156                 18           0   0
8               LB,RB             25-180                 90           0   1
9               CB,LB             26-240                 76           0   0
10                 LB             36-255                 14           0   0
11                 CB             25-033                 86           1   0
12                 CB             32-204                  4           0   0
13                 RB             26-305                 73           0   0
14                 CB             31-193                 17           0   0
15                 GK             28-165                 90           0   0
16                NaN                NaN                990           3   3

             ... SCA     Passes                  Carries      Take-Ons
   PK PKatt  ... SCA GCA    Cmp  Att   Cmp% PrgP Carries PrgC      Att Succ
0   0     0  ...   6   0     23   28   82.1    3      26    1        3    3
1   0     0  ...   3   0     18   22   81.8    1      22    4        3    0
2   0     0  ...   1   0      6    6  100.0    0      12    1        1    0
3   0     0  ...  10   1     55   62   88.7    9      42   13        1    0
4   0     0  ...   3   1     36   42   85.7   10      35    4        5    3
5   0     0  ...   1   0     50   58   86.2    2      39    0        4    2
6   0     0  ...   5   2     42   47   89.4    6      24    2        0    0
7   0     0  ...   1   0     13   13  100.0    0       9    0        1    0
8   0     0  ...   3   1     78   86   90.7    3      61    0        2    1
9   0     0  ...   0   0     58   60   96.7    3      43    1        1    1
10  0     0  ...   1   0     18   18  100.0    2       8    0        0    0
11  0     0  ...   1   0     59   64   92.2    3      50    0        0    0
12  0     0  ...   1   1     22   24   91.7    5      20    0        0    0
13  0     0  ...   3   0     43   50   86.0    5      28    1        3    3
14  0     0  ...   0   0     25   25  100.0    2      18    0        1    1
15  0     0  ...   0   0     30   35   85.7    0      29    0        0    0
16  0     0  ...  39   6    576  640   90.0   54     466   27       25   14

[17 rows x 31 columns]
----------------------------------
       Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                   Player                  #             Nation
0          Joshua Zirkzee               11.0             nl NED
1         Marcus Rashford               10.0            eng ENG
2      Alejandro Garnacho               17.0             ar ARG
3             Amad Diallo               16.0             ci CIV
4          Rasmus Højlund                9.0             dk DEN
5         Bruno Fernandes                8.0             pt POR
6       Christian Eriksen               14.0             dk DEN
7   Manuel Ugarte Ribeiro               25.0             uy URU
8           Kobbie Mainoo               37.0            eng ENG
9             Diogo Dalot               20.0             pt POR
10      Lisandro Martínez                6.0             ar ARG
11       Matthijs de Ligt                4.0             nl NED
12      Noussair Mazraoui                3.0             ma MAR
13            André Onana               24.0             cm CMR
14             14 Players                NaN                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Performance      \
                  Pos                Age                Min         Gls Ast
0                  FW             23-122                 60           0   0
1               LW,FW             26-326                 30           0   0
2               LW,RW             20-082                 90           0   0
3                  RW             22-072                 75           0   0
4                  FW             21-230                 15           0   0
5                  AM             30-013                 90           0   0
6                  DM             32-220                 75           0   0
7                  DM             23-163                 15           0   0
8                  DM             19-155                 90           0   0
9                  LB             25-187                 90           0   0
10                 CB             26-247                 90           0   0
11                 CB             25-040                 90           0   0
12                 RB             26-312                 90           0   0
13                 GK             28-172                 90           0   0
14                NaN                NaN                990           0   0

             ... SCA     Passes                 Carries      Take-Ons
   PK PKatt  ... SCA GCA    Cmp  Att  Cmp% PrgP Carries PrgC      Att Succ
0   0     0  ...   3   0     15   17  88.2    2       6    1        0    0
1   0     0  ...   0   0      6   10  60.0    1       7    0        0    0
2   0     0  ...   2   0     20   23  87.0    0      27    4        2    0
3   0     0  ...   4   0     30   37  81.1    3      30    3        4    0
4   0     0  ...   0   0      2    4  50.0    0       5    1        0    0
5   0     0  ...   7   0     62   91  68.1   14      61    2        2    2
6   0     0  ...   5   0     55   69  79.7    7      41    0        0    0
7   0     0  ...   0   0     13   14  92.9    0      12    0        1    0
8   0     0  ...   1   0     42   46  91.3    7      39    2        0    0
9   0     0  ...   4   0     62   67  92.5    9      44    3        2    2
10  0     0  ...   1   0     97  113  85.8    8      86    0        0    0
11  0     0  ...   0   0     78   83  94.0    0      75    0        0    0
12  0     0  ...   0   0     65   78  83.3    6      55    2        5    3
13  0     0  ...   0   0     39   46  84.8    0      36    0        0    0
14  0     0  ...  27   0    586  698  84.0   57     524   18       16    7

[15 rows x 31 columns]
----------------------------------

In [1104]:
countries = list()
for p, v in all_players_dict.items():
    countries.append(v['national_team'])

In [1107]:
with open("match_reports.pkl","wb") as f:
    pkl.dump(match_reports,f)

In [1106]:
len(countries)

91